include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    cancel_subscriptions: true
    close_sinks: true
    directives_ordering: true
    discarded_futures: true
    secure_pubspec_urls: true
    strict_top_level_inference: true
    unawaited_futures: true
    unnecessary_await_in_return: true
