include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    depend_on_referenced_packages: error
    discarded_futures: error
    implementation_imports: error
    unawaited_futures: error
  exclude:
    - build/**
    - third_party/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
