// Generated by js/build.mjs.
const cookingBundleRevision = 'b3f161471c9608ffed3dc610808d4762e9f5a9ad4b2a99bc59a97282024c65cc';
const cookingEngineRevision = 'quickjs-ng-v0.17.0-6d46d07d04041b40f4f49eaa7fdebe44c314c699';
const bundledCookingModules = <String, Map<String, String>>{'spoiler-alert': {'owner':'cooking','version':'1','stage':'syntax'},'offline-missing-uploads': {'owner':'cooking','version':'1','stage':'syntax'},'fixture-mark': {'owner':'cooking-fixture','version':'1','stage':'syntax'},'fixture-tokens': {'owner':'cooking-fixture','version':'1','stage':'token'},'fixture-document': {'owner':'cooking-fixture','version':'1','stage':'document'}};
