import { build } from 'esbuild';
import { assembleModules, validateBundle } from './module-assembly.mjs';
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
const root = dirname(fileURLToPath(import.meta.url));
const sha = bytes => createHash('sha256').update(bytes).digest('hex');
const provenance = JSON.parse(readFileSync(join(root,'provenance.json')));
for (const [path,hash] of Object.entries(provenance.sha256)) {
  if (sha(readFileSync(join(root,'vendor',path))) !== hash) throw Error(`Vendor hash mismatch: ${path}`);
}
const modules=JSON.parse(readFileSync(join(root,'src/modules/catalog.json')));
const ids=new Set();
for(const m of modules) {
 if(ids.has(m.id)||!m.id||!m.owner||!m.version||!['syntax','token','document'].includes(m.stage)||!/^[a-z-]+\.js$/.test(m.source)) throw Error('Invalid module catalog');
 ids.add(m.id);
 for(const [tag,attrs] of Object.entries(m.policy)) {
  if(!/^(?:mark|span|div|details|summary|time|kbd|abbr|a|pre|code|aside|li|p|ol|ul|blockquote|table|td|th)$/.test(tag)||!attrs.every(a=>/^(?:class|title|datetime|data-[a-z0-9-]+|aria-[a-z0-9-]+)$/.test(a) && (!/^data-.*(?:url|href|src)/.test(a) || ['data-orig-href','data-orig-src'].includes(a)))) throw Error('Unsafe module HTML policy');
 }
}
const moduleSource=assembleModules(modules);
const modulePlugin={name:'bundled-module-catalog',setup(b){b.onResolve({filter:/^bundled-modules$/},()=>({path:'catalog',namespace:'catalog'}));b.onLoad({filter:/.*/,namespace:'catalog'},()=>({contents:moduleSource,resolveDir:join(root,'src'),loader:'js'}));}};
const aliases = {
  'discourse-i18n':join(root,'src/i18n.js'),
  'discourse/lib/deprecated':join(root,'src/deprecated.js'),
  ...Object.fromEntries(['object','escape','case-converter'].map(n => [`discourse/lib/${n}`,join(root,`vendor/frontend/discourse/app/lib/${n}.js`)])),
  'pretty-text/inline-oneboxer':join(root,'src/onebox-cache.js'),
  'pretty-text/oneboxer-cache':join(root,'src/onebox-cache.js'),
};
const result = await build({
  absWorkingDir:root, entryPoints:['src/entry.js'], bundle:true, write:false,
  platform:'neutral', mainFields:['module','main'], format:'iife', target:'es2022', charset:'ascii',
  legalComments:'inline', inject:[join(root,'src/environment.js')],
  plugins:[modulePlugin,{ name:'closed-import-allowlist',setup(b) {
    b.onResolve({filter:/^(?:discourse(?:-i18n|\/)|pretty-text\/)/},args => {
      if (aliases[args.path]) return {path:aliases[args.path]};
      if (/^pretty-text\/(allow-lister|guid|sanitizer|text-replace|emoji(?:\/data|\/version)?|mentions|censored-words)$/.test(args.path)) return {path:join(root,`vendor/frontend/pretty-text/addon/${args.path.slice('pretty-text/'.length)}.js`)};
      throw Error(`Non-allowlisted import: ${args.path}`);
    });
  }}], metafile:true,
});
const bundle = `// Discourse ${provenance.revision}; generated by js/build.mjs. See js/NOTICE.txt.\n`+result.outputFiles[0].text+'\n"ready";\n';
validateBundle(bundle);
const dartLiteral = bundle.split("'''").map(part => "r'''"+part+"'''").join(' "\'\'\'" ');
const dart = `// GENERATED FILE. Run node js/build.mjs; do not edit.\n// ignore_for_file: lines_longer_than_80_chars\nconst String cookingBundle = ${dartLiteral};\n`;
const notices = ['Discourse offline cooking bundle\n',
  `Discourse source: ${provenance.repository} at ${provenance.revision}\nGPL-2.0-only. Complete bundled source is in vendor/. Full license: vendor/LICENSE.txt.\n`,
  'Local adapters and final output policy are in src/. They replace Ruby/browser lookups with per-request memory snapshots. No upstream source files are edited.\n'];
// Include licenses of every npm dependency whose source is bundled.
const names = [...new Set(Object.keys(result.metafile.inputs).filter(p=>p.startsWith('node_modules/')).map(p=>p.split('/')[1]))].sort();
for (const name of names) {
  const dir=join(root,'node_modules',name);
  const pkg=JSON.parse(readFileSync(join(dir,'package.json')));
  notices.push(`\n--- ${name} ${pkg.version} (${pkg.license}) ---\n`);
  const licenses=readdirSync(dir).filter(n=>/^licen[sc]e(?:[-.]|$)/i.test(n));
  if (!licenses.length) throw Error(`No license file for ${name}`);
  for(const file of licenses) notices.push(readFileSync(join(dir,file),'utf8')+'\n');
}
// Flutter discovers licenses at a package's root. Keep all redistributed
// engine/dependency terms there, not only in nested source directories.
const packageLicense = [
  'discourse_cooking — component license notices',
  'Generated by js/build.mjs. These scope headers do not alter upstream terms.',
  '=== Discourse cooking engine and spoiler feature: GPL-2.0-only ===',
  readFileSync(join(root,'vendor/LICENSE.txt'),'utf8'),
  '=== Bundled JavaScript dependency notices ===',
  notices.join('\n'),
  '=== Native QuickJS engine: MIT ===',
  readFileSync(join(root,'../vendor/quickjs/LICENSE'),'utf8'),
  '=== Local adapters and build tooling ===',
  'Local project code remains covered by the repository root LICENSE. The root MIT license does not relicense the GPL-covered Discourse source or combined bundle.',
].join('\n\n')+'\n';
const manifest = {
  discourseRevision:provenance.revision,
  bundleSha256:sha(bundle),
  vendorManifestSha256:sha(readFileSync(join(root,'provenance.json'))),
  npmLockSha256:sha(readFileSync(join(root,'package-lock.json'))),
  moduleAssemblySha256:sha(readFileSync(join(root,'module-assembly.mjs'))),
  moduleCatalogSha256:sha(readFileSync(join(root,'src/modules/catalog.json'))),
  inputs:Object.fromEntries(Object.keys(result.metafile.inputs).filter(p=>!p.startsWith('catalog:')).sort().map(p=>[p,sha(readFileSync(join(root,p)))])),
};
const engineProvenance=JSON.parse(readFileSync(join(root,'../vendor/quickjs/PROVENANCE.json')));
const moduleDart = `// Generated by js/build.mjs.\nconst cookingBundleRevision = '${sha(bundle)}';\nconst cookingEngineRevision = 'quickjs-ng-${engineProvenance.tag}-${engineProvenance.commit}';\nconst bundledCookingModules = <String, Map<String, String>>{${modules.map(m=>`'${m.id}': {'owner':'${m.owner}','version':'${m.version}','stage':'${m.stage}'}`).join(',')}};\n`;
const outputs = {
  '../lib/src/generated_modules.dart':moduleDart,
  '../assets/cooking.js':bundle,
  '../lib/src/generated_bundle.dart':dart,
  'NOTICE.txt':notices.join('\n'),
  '../LICENSE':packageLicense,
  'bundle-manifest.json':JSON.stringify(manifest,null,2)+'\n',
};
for(const [path,content] of Object.entries(outputs)) {
  const dest=join(root,path);
  if (process.argv.includes('--check')) {
    if(readFileSync(dest,'utf8')!==content) throw Error(`Stale generated file: ${relative(root,dest)}`);
  } else { mkdirSync(dirname(dest),{recursive:true}); writeFileSync(dest,content); }
}
console.log(`Bundle ${Buffer.byteLength(bundle)} bytes; sha256 ${sha(bundle)}`);
