library;

import 'dart:io';

const String _output = 'lib/src/theme/d_icons.dart';
const String _manifest = 'tool/icons.txt';

typedef _Icon = ({String name, String lucide});

void main() {
  final (icons, aliases) = _readManifest();
  final names = icons.map((icon) => icon.name).toSet();
  final danglingAliases = aliases.entries.where(
    (entry) => !names.contains(entry.value),
  );
  for (final alias in danglingAliases) {
    stderr.writeln(
      'Alias "${alias.key}" points at "${alias.value}", which is not listed.',
    );
    exit(1);
  }

  File(_output).writeAsStringSync(_render(icons, aliases));
  final format = Process.runSync(Platform.resolvedExecutable, [
    'format',
    _output,
  ]);
  if (format.exitCode != 0) {
    stderr.write(format.stderr);
    exit(format.exitCode);
  }
  stdout.writeln(
    'Wrote $_output — ${icons.length} Lucide icons, '
    '${aliases.length} aliases',
  );
}

(List<_Icon>, Map<String, String>) _readManifest() {
  final icons = <_Icon>[];
  final aliases = <String, String>{};

  for (final raw in File(_manifest).readAsLinesSync()) {
    final line = raw.trim();
    if (line.isEmpty || line.startsWith('#')) continue;
    if (line.contains('=')) {
      final [alias, target] = line.split('=').map((p) => p.trim()).toList();
      aliases[alias] = target;
    } else {
      final parts = line.split(':').map((part) => part.trim()).toList();
      if (parts.length != 2 || parts.any((part) => part.isEmpty)) {
        stderr.writeln('Expected "discourse-name: lucideIdentifier": $line');
        exit(1);
      }
      icons.add((name: parts.first, lucide: parts.last));
    }
  }

  final duplicateNames = <String>{};
  final seenNames = <String>{};
  for (final icon in icons) {
    if (!seenNames.add(icon.name)) duplicateNames.add(icon.name);
  }
  if (duplicateNames.isNotEmpty) {
    stderr.writeln('Duplicate icons: ${duplicateNames.join(', ')}');
    exit(1);
  }

  return (icons, aliases);
}

String _render(List<_Icon> icons, Map<String, String> aliases) {
  final buffer = StringBuffer()
    ..writeln('// GENERATED BY tool/gen_icons.dart — DO NOT EDIT.')
    ..writeln('//')
    ..writeln('// Discourse icon names mapped to Lucide 24x24 outline glyphs.')
    ..writeln()
    ..writeln("import 'package:lucide_flutter/lucide_flutter.dart';")
    ..writeln()
    ..writeln("import 'd_icon.dart';")
    ..writeln()
    ..writeln('/// Every icon in `tool/icons.txt`, as [DIconData].')
    ..writeln('abstract final class DIcons {');

  for (final icon in icons) {
    buffer
      ..writeln(
        '  static const DIconData ${_identifier(icon.name)} = DIconData(',
      )
      ..writeln("    '${icon.name}',")
      ..writeln('    LucideIcons.${icon.lucide},')
      ..writeln('  );')
      ..writeln();
  }

  buffer
    ..writeln('  /// Icons by the name Discourse uses, aliases included, for')
    ..writeln('  /// the places where a name arrives as a string.')
    ..writeln('  static const Map<String, DIconData> byName = {');
  for (final icon in icons) {
    buffer.writeln("    '${icon.name}': ${_identifier(icon.name)},");
  }
  for (final MapEntry(key: alias, value: target) in aliases.entries) {
    buffer.writeln("    '$alias': ${_identifier(target)},");
  }
  buffer
    ..writeln('  };')
    ..writeln('}');

  return buffer.toString();
}

String _identifier(String name) {
  final parts = name.split('-');
  return [
    parts.first,
    ...parts.skip(1).map((p) => p[0].toUpperCase() + p.substring(1)),
  ].join();
}
