import 'dart:io';

/// Keeps self-contained styleguide usage identical to the runnable examples.
void main() {
  final examples = File(
    'lib/src/styleguide/examples/empty_examples.dart',
  ).readAsStringSync();
  final artwork = File(
    'lib/src/styleguide/examples/empty_artwork.dart',
  ).readAsStringSync();
  final sample = examples.substring(
    examples.indexOf('class _EmptySample '),
    examples.indexOf('/// Local form fixture'),
  );
  final search = examples.substring(
    examples.indexOf('class EmptySearchSample '),
    examples.indexOf('String _exampleCode'),
  );
  const imports = '''import 'package:discourse_native/discourse_ui.dart';
import 'package:discourse_native/src/styleguide/styleguide_chrome.dart';
import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
''';
  File(
    'lib/src/styleguide/examples/empty_example_source.dart',
  ).writeAsStringSync(
    '// Generated by dart run tool/generate_empty_example_source.dart.\n'
    'const emptySampleSource = r"""$imports\n$sample\n${artwork.substring(artwork.indexOf('Widget emptyReferenceIcon'))}""";\n'
    'const emptySearchSource = r"""$imports\n$search""";\n',
  );
}
