import 'dart:io';

void main(List<String> arguments) {
  final source = File(
    'lib/src/styleguide/examples/radio_group_examples.dart',
  ).readAsStringSync();
  final reference = source.indexOf('class _Reference extends');
  final form = source.indexOf('class _FormPreview extends');
  final readOnly = source.indexOf('class _ReadOnlyPreview extends');
  final snippets = {
    'reference': source.substring(reference, form),
    'form': source.substring(form, readOnly),
    'readOnly': source.substring(readOnly),
  };
  final generated =
      '// Generated by tool/generate_radio_group_example_sources.dart.\n'
      'const radioGroupExampleSources = <String, String>{\n'
      '${snippets.entries.map((entry) => "  '${entry.key}': r'''${entry.value}''',\n").join()}'
      '};\n';
  final output = File(
    'lib/src/styleguide/examples/radio_group_example_sources.dart',
  );
  if (arguments.contains('--check')) {
    if (!output.existsSync() || output.readAsStringSync() != generated) {
      stderr.writeln('Radio Group snippets are stale. Run this generator.');
      exitCode = 1;
    }
  } else {
    output.writeAsStringSync(generated);
  }
}
