import 'dart:io';

/// Keep the styleguide's complete runnable snippets equal to its real examples.
void main() {
  final source = File(
    'lib/src/styleguide/examples/field_examples.dart',
  ).readAsStringSync();
  final helpers = source.substring(
    source.indexOf('class _Editor'),
    source.indexOf('class FieldPaymentExample'),
  );
  const examples = {
    'payment': 'Payment',
    'editors': 'Editors',
    'slider': 'Slider',
    'address': 'Address',
    'checkbox': 'Checkbox',
    'choice': 'Choice',
    'notifications': 'Notifications',
    'responsive': 'Responsive',
  };
  final names = examples.values.toList();
  final snippets = <String, String>{};
  for (final entry in examples.entries) {
    final index = names.indexOf(entry.value);
    final start = source.indexOf('class Field${entry.value}Example');
    final end = index + 1 < names.length
        ? source.indexOf('class Field${names[index + 1]}Example')
        : source.length;
    snippets[entry.key] =
        "import 'package:discourse_native/discourse_ui.dart';\n"
        "import 'package:flutter/material.dart';\n\n"
        'void main() => runApp(MaterialApp(home: Scaffold(body: SingleChildScrollView('
        'padding: const EdgeInsets.all(24), child: Field${entry.value}Example()))));\n\n'
        '$helpers${source.substring(start, end)}';
  }
  snippets['rtl'] = snippets['payment']!.replaceFirst(
    'child: FieldPaymentExample()',
    'child: Directionality(textDirection: TextDirection.rtl, child: FieldPaymentExample(arabic: true))',
  );
  File(
    'lib/src/styleguide/examples/field_example_sources.dart',
  ).writeAsStringSync(
    '// Generated by tool/generate_field_example_sources.dart.\n'
    'const fieldExampleSources = <String, String>{\n'
    '${snippets.entries.map((entry) => "  '${entry.key}': r'''${entry.value}''',\n").join()}'
    '};\n',
  );
}
