import 'dart:convert';
import 'dart:io';

/// Rebuilds styleguide reference metadata from the frozen project catalogue.
void main() {
  final snapshot =
      jsonDecode(
            File('docs/component-library/catalogue.json').readAsStringSync(),
          )
          as Map<String, dynamic>;
  final components = snapshot['components'] as List<dynamic>;
  String literal(String value) => jsonEncode(value).replaceAll(r'$', r'\$');
  final output = StringBuffer()
    ..writeln('// Generated by tool/generate_component_catalogue.dart.')
    ..writeln("import 'styleguide_example.dart';")
    ..writeln()
    ..writeln(
      'const componentReferenceDate = ${literal(snapshot['referenceDate'] as String)};',
    )
    ..writeln('const componentCatalogue = <ComponentReference>[');
  for (final item in components.cast<Map<String, dynamic>>()) {
    output
      ..writeln('  ComponentReference(')
      ..writeln('    id: ${literal(item['id'] as String)},')
      ..writeln('    name: ${literal(item['name'] as String)},')
      ..writeln('    url: ${literal(item['referenceUrl'] as String)},')
      ..writeln('    sections: [');
    for (final section
        in (item['documentedSections'] as List<dynamic>).cast<String>()) {
      output.writeln('      ${literal(section)},');
    }
    output
      ..writeln('    ],')
      ..writeln('  ),');
  }
  output.writeln('];');
  final file = File('lib/src/styleguide/component_catalogue.dart');
  file.writeAsStringSync(output.toString());
  final result = Process.runSync(Platform.resolvedExecutable, [
    'format',
    file.path,
  ]);
  stdout.write(result.stdout);
  stderr.write(result.stderr);
  exitCode = result.exitCode;
}
