// GENERATED BY tool/gen_icons.dart — DO NOT EDIT.
//
// Discourse icon names mapped to Lucide 24x24 outline glyphs.

import 'package:lucide_flutter/lucide_flutter.dart';

import 'd_icon.dart';

/// Every icon in `tool/icons.txt`, as [DIconData].
abstract final class DIcons {
  static const DIconData layerGroup = DIconData(
    'layer-group',
    LucideIcons.layers,
  );

  static const DIconData house = DIconData('house', LucideIcons.house);

  static const DIconData asterisk = DIconData('asterisk', LucideIcons.asterisk);

  static const DIconData circle = DIconData('circle', LucideIcons.circle);

  static const DIconData fire = DIconData('fire', LucideIcons.flame);

  static const DIconData envelope = DIconData('envelope', LucideIcons.mail);

  static const DIconData inbox = DIconData('inbox', LucideIcons.inbox);

  static const DIconData list = DIconData('list', LucideIcons.list);

  static const DIconData globe = DIconData('globe', LucideIcons.globe);

  static const DIconData gear = DIconData('gear', LucideIcons.settings);

  static const DIconData bug = DIconData('bug', LucideIcons.bug);

  static const DIconData wrench = DIconData('wrench', LucideIcons.wrench);

  static const DIconData ellipsis = DIconData('ellipsis', LucideIcons.ellipsis);

  static const DIconData ellipsisVertical = DIconData(
    'ellipsis-vertical',
    LucideIcons.ellipsisVertical,
  );

  static const DIconData farPenToSquare = DIconData(
    'far-pen-to-square',
    LucideIcons.squarePen,
  );

  static const DIconData chevronRight = DIconData(
    'chevron-right',
    LucideIcons.chevronRight,
  );

  static const DIconData chevronLeft = DIconData(
    'chevron-left',
    LucideIcons.chevronLeft,
  );

  static const DIconData chevronDown = DIconData(
    'chevron-down',
    LucideIcons.chevronDown,
  );

  static const DIconData chevronUp = DIconData(
    'chevron-up',
    LucideIcons.chevronUp,
  );

  static const DIconData xmark = DIconData('xmark', LucideIcons.x);

  static const DIconData arrowLeft = DIconData(
    'arrow-left',
    LucideIcons.arrowLeft,
  );

  static const DIconData arrowUp = DIconData('arrow-up', LucideIcons.arrowUp);

  static const DIconData arrowDown = DIconData(
    'arrow-down',
    LucideIcons.arrowDown,
  );

  static const DIconData arrowRotateLeft = DIconData(
    'arrow-rotate-left',
    LucideIcons.rotateCcw,
  );

  static const DIconData upRightFromSquare = DIconData(
    'up-right-from-square',
    LucideIcons.externalLink,
  );

  static const DIconData rightFromBracket = DIconData(
    'right-from-bracket',
    LucideIcons.logOut,
  );

  static const DIconData shuffle = DIconData('shuffle', LucideIcons.shuffle);

  static const DIconData plus = DIconData('plus', LucideIcons.plus);

  static const DIconData minus = DIconData('minus', LucideIcons.minus);

  static const DIconData circlePlus = DIconData(
    'circle-plus',
    LucideIcons.circlePlus,
  );

  static const DIconData circleMinus = DIconData(
    'circle-minus',
    LucideIcons.circleMinus,
  );

  static const DIconData circleInfo = DIconData(
    'circle-info',
    LucideIcons.info,
  );

  static const DIconData triangleExclamation = DIconData(
    'triangle-exclamation',
    LucideIcons.triangleAlert,
  );

  static const DIconData exclamation = DIconData(
    'exclamation',
    LucideIcons.circleAlert,
  );

  static const DIconData magnifyingGlass = DIconData(
    'magnifying-glass',
    LucideIcons.search,
  );

  static const DIconData filter = DIconData('filter', LucideIcons.filter);

  static const DIconData copy = DIconData('copy', LucideIcons.copy);

  static const DIconData play = DIconData('play', LucideIcons.play);

  static const DIconData pause = DIconData('pause', LucideIcons.pause);

  static const DIconData snowflake = DIconData(
    'snowflake',
    LucideIcons.snowflake,
  );

  static const DIconData microphoneLines = DIconData(
    'microphone-lines',
    LucideIcons.micAudioLines,
  );

  static const DIconData microphoneSlash = DIconData(
    'microphone-slash',
    LucideIcons.micOff,
  );

  static const DIconData closedCaptioning = DIconData(
    'closed-captioning',
    LucideIcons.captions,
  );

  static const DIconData video = DIconData('video', LucideIcons.video);

  static const DIconData videoSlash = DIconData(
    'video-slash',
    LucideIcons.videoOff,
  );

  static const DIconData display = DIconData('display', LucideIcons.monitor);

  static const DIconData earListen = DIconData('ear-listen', LucideIcons.ear);

  static const DIconData hand = DIconData('hand', LucideIcons.hand);

  static const DIconData phoneSlash = DIconData(
    'phone-slash',
    LucideIcons.phoneOff,
  );

  static const DIconData expand = DIconData('expand', LucideIcons.maximize2);

  static const DIconData discourseCompress = DIconData(
    'discourse-compress',
    LucideIcons.minimize2,
  );

  static const DIconData discourseExpand = DIconData(
    'discourse-expand',
    LucideIcons.maximize2,
  );

  static const DIconData chevronsLeft = DIconData(
    'chevrons-left',
    LucideIcons.chevronsLeft,
  );

  static const DIconData chevronsRight = DIconData(
    'chevrons-right',
    LucideIcons.chevronsRight,
  );

  static const DIconData farFileLines = DIconData(
    'far-file-lines',
    LucideIcons.fileText,
  );

  static const DIconData comment = DIconData(
    'comment',
    LucideIcons.messageCircle,
  );

  static const DIconData comments = DIconData(
    'comments',
    LucideIcons.messagesSquare,
  );

  static const DIconData quoteLeft = DIconData('quote-left', LucideIcons.quote);

  static const DIconData reply = DIconData('reply', LucideIcons.reply);

  static const DIconData share = DIconData('share', LucideIcons.share2);

  static const DIconData thumbtack = DIconData('thumbtack', LucideIcons.pin);

  static const DIconData lock = DIconData('lock', LucideIcons.lock);

  static const DIconData unlock = DIconData('unlock', LucideIcons.lockOpen);

  static const DIconData folder = DIconData('folder', LucideIcons.folder);

  static const DIconData folderOpen = DIconData(
    'folder-open',
    LucideIcons.folderOpen,
  );

  static const DIconData farEye = DIconData('far-eye', LucideIcons.eye);

  static const DIconData farEyeSlash = DIconData(
    'far-eye-slash',
    LucideIcons.eyeOff,
  );

  static const DIconData handPointRight = DIconData(
    'hand-point-right',
    LucideIcons.pointer,
  );

  static const DIconData trashCan = DIconData('trash-can', LucideIcons.trash2);

  static const DIconData pencil = DIconData('pencil', LucideIcons.pencil);

  static const DIconData flag = DIconData('flag', LucideIcons.flag);

  static const DIconData certificate = DIconData(
    'certificate',
    LucideIcons.award,
  );

  static const DIconData bookmark = DIconData('bookmark', LucideIcons.bookmark);

  static const DIconData farBookmark = DIconData(
    'far-bookmark',
    LucideIcons.bookmark,
  );

  static const DIconData heart = DIconData('heart', LucideIcons.heart);

  static const DIconData farHeart = DIconData('far-heart', LucideIcons.heart);

  static const DIconData star = DIconData('star', LucideIcons.star);

  static const DIconData farStar = DIconData('far-star', LucideIcons.star);

  static const DIconData user = DIconData('user', LucideIcons.user);

  static const DIconData users = DIconData('users', LucideIcons.users);

  static const DIconData userPlus = DIconData(
    'user-plus',
    LucideIcons.userPlus,
  );

  static const DIconData at = DIconData('at', LucideIcons.atSign);

  static const DIconData bell = DIconData('bell', LucideIcons.bellRing);

  static const DIconData farBell = DIconData('far-bell', LucideIcons.bell);

  static const DIconData discourseBellExclamation = DIconData(
    'discourse-bell-exclamation',
    LucideIcons.bellDot,
  );

  static const DIconData discourseBellSlash = DIconData(
    'discourse-bell-slash',
    LucideIcons.bellOff,
  );

  static const DIconData paperPlane = DIconData(
    'paper-plane',
    LucideIcons.send,
  );

  static const DIconData toggleOn = DIconData(
    'toggle-on',
    LucideIcons.toggleRight,
  );

  static const DIconData toggleOff = DIconData(
    'toggle-off',
    LucideIcons.toggleLeft,
  );

  static const DIconData farFaceSmile = DIconData(
    'far-face-smile',
    LucideIcons.smile,
  );

  static const DIconData paperclip = DIconData(
    'paperclip',
    LucideIcons.paperclip,
  );

  static const DIconData mapPin = DIconData('map-pin', LucideIcons.mapPin);

  static const DIconData discourseEmojis = DIconData(
    'discourse-emojis',
    LucideIcons.smilePlus,
  );

  static const DIconData flask = DIconData('flask', LucideIcons.flaskConical);

  static const DIconData discourseFlaskCheck = DIconData(
    'discourse-flask-check',
    LucideIcons.flaskConical,
  );

  static const DIconData quoteRight = DIconData(
    'quote-right',
    LucideIcons.quote,
  );

  static const DIconData link = DIconData('link', LucideIcons.link);

  static const DIconData check = DIconData('check', LucideIcons.check);

  static const DIconData farClock = DIconData('far-clock', LucideIcons.clock);

  static const DIconData discourseBookmarkClock = DIconData(
    'discourse-bookmark-clock',
    LucideIcons.alarmClock,
  );

  static const DIconData bold = DIconData('bold', LucideIcons.bold);

  static const DIconData italic = DIconData('italic', LucideIcons.italic);

  static const DIconData upload = DIconData('upload', LucideIcons.upload);

  static const DIconData calendar = DIconData('calendar', LucideIcons.calendar);

  static const DIconData keyboard = DIconData('keyboard', LucideIcons.keyboard);

  static const DIconData image = DIconData('image', LucideIcons.image);

  static const DIconData imageOff = DIconData(
    'image-off',
    LucideIcons.imageOff,
  );

  static const DIconData images = DIconData('images', LucideIcons.images);

  static const DIconData imagePlus = DIconData(
    'image-plus',
    LucideIcons.imagePlus,
  );

  static const DIconData slidersHorizontal = DIconData(
    'sliders-horizontal',
    LucideIcons.slidersHorizontal,
  );

  static const DIconData zoomIn = DIconData('zoom-in', LucideIcons.zoomIn);

  static const DIconData zoomOut = DIconData('zoom-out', LucideIcons.zoomOut);

  static const DIconData grid2x2X = DIconData(
    'grid-2x2-x',
    LucideIcons.grid2x2X,
  );

  static const DIconData grid3x3 = DIconData('grid-3x3', LucideIcons.grid3x3);

  static const DIconData galleryHorizontal = DIconData(
    'gallery-horizontal',
    LucideIcons.galleryHorizontal,
  );

  static const DIconData squareCheck = DIconData(
    'square-check',
    LucideIcons.squareCheck,
  );

  static const DIconData square = DIconData('square', LucideIcons.square);

  static const DIconData circleDot = DIconData(
    'circle-dot',
    LucideIcons.circleDot,
  );

  static const DIconData tag = DIconData('tag', LucideIcons.tag);

  static const DIconData arrowsRotate = DIconData(
    'arrows-rotate',
    LucideIcons.refreshCw,
  );

  static const DIconData download = DIconData('download', LucideIcons.download);

  static const DIconData farCircleCheck = DIconData(
    'far-circle-check',
    LucideIcons.circleCheckBig,
  );

  /// Icons by the name Discourse uses, aliases included, for
  /// the places where a name arrives as a string.
  static const Map<String, DIconData> byName = {
    'layer-group': layerGroup,
    'house': house,
    'asterisk': asterisk,
    'circle': circle,
    'fire': fire,
    'envelope': envelope,
    'inbox': inbox,
    'list': list,
    'globe': globe,
    'gear': gear,
    'bug': bug,
    'wrench': wrench,
    'ellipsis': ellipsis,
    'ellipsis-vertical': ellipsisVertical,
    'far-pen-to-square': farPenToSquare,
    'chevron-right': chevronRight,
    'chevron-left': chevronLeft,
    'chevron-down': chevronDown,
    'chevron-up': chevronUp,
    'xmark': xmark,
    'arrow-left': arrowLeft,
    'arrow-up': arrowUp,
    'arrow-down': arrowDown,
    'arrow-rotate-left': arrowRotateLeft,
    'up-right-from-square': upRightFromSquare,
    'right-from-bracket': rightFromBracket,
    'shuffle': shuffle,
    'plus': plus,
    'minus': minus,
    'circle-plus': circlePlus,
    'circle-minus': circleMinus,
    'circle-info': circleInfo,
    'triangle-exclamation': triangleExclamation,
    'exclamation': exclamation,
    'magnifying-glass': magnifyingGlass,
    'filter': filter,
    'copy': copy,
    'play': play,
    'pause': pause,
    'snowflake': snowflake,
    'microphone-lines': microphoneLines,
    'microphone-slash': microphoneSlash,
    'closed-captioning': closedCaptioning,
    'video': video,
    'video-slash': videoSlash,
    'display': display,
    'ear-listen': earListen,
    'hand': hand,
    'phone-slash': phoneSlash,
    'expand': expand,
    'discourse-compress': discourseCompress,
    'discourse-expand': discourseExpand,
    'chevrons-left': chevronsLeft,
    'chevrons-right': chevronsRight,
    'far-file-lines': farFileLines,
    'comment': comment,
    'comments': comments,
    'quote-left': quoteLeft,
    'reply': reply,
    'share': share,
    'thumbtack': thumbtack,
    'lock': lock,
    'unlock': unlock,
    'folder': folder,
    'folder-open': folderOpen,
    'far-eye': farEye,
    'far-eye-slash': farEyeSlash,
    'hand-point-right': handPointRight,
    'trash-can': trashCan,
    'pencil': pencil,
    'flag': flag,
    'certificate': certificate,
    'bookmark': bookmark,
    'far-bookmark': farBookmark,
    'heart': heart,
    'far-heart': farHeart,
    'star': star,
    'far-star': farStar,
    'user': user,
    'users': users,
    'user-plus': userPlus,
    'at': at,
    'bell': bell,
    'far-bell': farBell,
    'discourse-bell-exclamation': discourseBellExclamation,
    'discourse-bell-slash': discourseBellSlash,
    'paper-plane': paperPlane,
    'toggle-on': toggleOn,
    'toggle-off': toggleOff,
    'far-face-smile': farFaceSmile,
    'paperclip': paperclip,
    'map-pin': mapPin,
    'discourse-emojis': discourseEmojis,
    'flask': flask,
    'discourse-flask-check': discourseFlaskCheck,
    'quote-right': quoteRight,
    'link': link,
    'check': check,
    'far-clock': farClock,
    'discourse-bookmark-clock': discourseBookmarkClock,
    'bold': bold,
    'italic': italic,
    'upload': upload,
    'calendar': calendar,
    'keyboard': keyboard,
    'image': image,
    'image-off': imageOff,
    'images': images,
    'image-plus': imagePlus,
    'sliders-horizontal': slidersHorizontal,
    'zoom-in': zoomIn,
    'zoom-out': zoomOut,
    'grid-2x2-x': grid2x2X,
    'grid-3x3': grid3x3,
    'gallery-horizontal': galleryHorizontal,
    'square-check': squareCheck,
    'square': square,
    'circle-dot': circleDot,
    'tag': tag,
    'arrows-rotate': arrowsRotate,
    'download': download,
    'far-circle-check': farCircleCheck,
    'd-liked': heart,
    'd-unliked': farHeart,
    'd-tracking': bell,
    'd-regular': farBell,
    'd-watching': discourseBellExclamation,
    'd-muted': discourseBellSlash,
    'topic.closed': lock,
    'topic.opened': unlock,
    'category.restricted': lock,
    'sidebar.all_categories': list,
    'user_menu.replies': reply,
    'user_menu.drafts': pencil,
    'notification.mentioned': at,
    'notification.group_mentioned': users,
    'notification.replied': reply,
    'notification.edited': pencil,
    'notification.liked': heart,
    'notification.liked_consolidated': heart,
    'notification.quoted': quoteRight,
    'notification.chat_quoted': quoteRight,
    'notification.private_message': envelope,
    'notification.invited_to_private_message': envelope,
    'notification.invited_to_topic': handPointRight,
    'notification.invitee_accepted': user,
    'notification.granted_badge': certificate,
    'notification.linked': link,
    'notification.linked_consolidated': link,
    'notification.moved_post': rightFromBracket,
    'notification.topic_reminder': farClock,
    'notification.bookmark_reminder': discourseBookmarkClock,
    'notification.group_message_summary': users,
    'notification.post_approved': check,
    'notification.membership_request_accepted': userPlus,
    'notification.membership_request_consolidated': users,
    'notification.reaction': discourseEmojis,
    'notification.votes_released': plus,
    'notification.upcoming_change_available': flask,
    'notification.upcoming_change_automatically_promoted': discourseFlaskCheck,
  };
}
