// Generated by dart run tool/generate_empty_example_source.dart.
const emptySampleSource =
    r"""import 'package:discourse_native/discourse_ui.dart';
import 'package:discourse_native/src/styleguide/styleguide_chrome.dart';
import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';

class _EmptySample extends StatefulWidget {
  const _EmptySample({required this.kind});
  final String kind;
  @override
  State<_EmptySample> createState() => _EmptySampleState();
}

class _EmptySampleState extends State<_EmptySample> {
  String? _result;

  @override
  Widget build(BuildContext context) {
    final kind = widget.kind;
    final rtl = kind == 'RTL';
    final tokens = DTokens.of(context);
    final (title, description, action) = switch (kind) {
      'Outline' => (
        'Cloud Storage Empty',
        'Upload files to your cloud storage to access them anywhere.',
        'Upload Files',
      ),
      'Background' => (
        'No Notifications',
        "You're all caught up. New notifications will appear here.",
        'Refresh',
      ),
      'Avatar' => (
        'User Offline',
        'This user is currently offline. You can leave a message to notify them or try again later.',
        'Leave Message',
      ),
      'Avatar Group' => (
        'No Team Members',
        'Invite your team to collaborate on this project.',
        'Invite Members',
      ),
      'RTL' => (
        'لا توجد مشاريع بعد',
        'لم تقم بإنشاء أي مشاريع بعد. ابدأ بإنشاء مشروعك الأول.',
        'إنشاء مشروع',
      ),
      _ => (
        'No Projects Yet',
        "You haven't created any projects yet. Get started by creating your first project.",
        'Create Project',
      ),
    };
    void act(String value) => setState(() => _result = value);
    final basic = kind == 'Basic' || rtl;
    return DDirection(
      textDirection: rtl ? TextDirection.rtl : null,
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          DEmpty(
            outlined: kind == 'Outline',
            backgroundColor: kind == 'Background'
                ? tokens.muted.withValues(alpha: tokens.muted.a * .3)
                : null,
            children: [
              DEmptyHeader(
                children: [
                  if (kind == 'Avatar' || kind == 'Avatar Group')
                    DEmptyMedia(
                      child: kind == 'Avatar'
                          ? _avatar('LR')
                          : DAvatarGroup(
                              children: [
                                for (final label in ['CN', 'LR', 'ER'])
                                  _avatar(label),
                              ],
                            ),
                    )
                  else
                    DEmptyMedia(
                      variant: DEmptyMediaVariant.icon,
                      child: Builder(
                        builder: (context) =>
                            emptyReferenceIcon(context, switch (kind) {
                              'Outline' => 'cloud',
                              'Background' => 'bell',
                              _ => 'folder-code',
                            }),
                      ),
                    ),
                  DEmptyTitle(title),
                  ConstrainedBox(
                    constraints: BoxConstraints(
                      maxWidth: kind == 'Background' ? 320 : 384,
                    ),
                    child: DEmptyDescription(description),
                  ),
                ],
              ),
              DEmptyContent(
                children: [
                  Wrap(
                    alignment: WrapAlignment.center,
                    spacing: 8,
                    runSpacing: 8,
                    children: [
                      StyleguideAction(
                        label: action,
                        outlined: kind == 'Outline' || kind == 'Background',
                        onPressed: () => act(action),
                      ),
                      if (basic)
                        StyleguideAction(
                          label: rtl ? 'استيراد مشروع' : 'Import Project',
                          outlined: true,
                          onPressed: () => act('Import Project'),
                        ),
                    ],
                  ),
                ],
              ),
              if (basic)
                StyleguideAction(
                  label: rtl ? 'تعرف على المزيد' : 'Learn More',
                  icon: rtl ? Icons.north_west : Icons.north_east,
                  onPressed: () => act('Project help opened'),
                ),
            ],
          ),
          if (_result != null)
            Semantics(liveRegion: true, child: Text(_result!)),
        ],
      ),
    );
  }
}

DAvatar _avatar(String label) => DAvatar(
  dimension: 48,
  semanticLabel: label,
  fallback: DAvatarFallback(child: Text(label)),
);


Widget emptyReferenceIcon(BuildContext context, String name) =>
    SvgPicture.string(
      _artwork[name]!,
      width: 16,
      height: 16,
      colorFilter: ColorFilter.mode(
        IconTheme.of(context).color!,
        BlendMode.srcIn,
      ),
    );

const _artwork = <String, String>{
  'folder-code': '''<!--
category: Document
tags: [program, develop, script, algorithm, compile, syntax, debug, software, compute, configure]
version: "2.10"
unicode: "f90f"
-->
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
>
  <path d="M11 19h-6a2 2 0 0 1 -2 -2v-11a2 2 0 0 1 2 -2h4l3 3h7a2 2 0 0 1 2 2v4" />
  <path d="M20 21l2 -2l-2 -2" />
  <path d="M17 17l-2 2l2 2" />
</svg>
''',
  'cloud': '''<!--
tags: [weather, online, cloud, storage, climate, forecast, server, sync, meteorology, atmospheric]
category: Weather
version: "1.0"
unicode: "ea76"
-->
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
>
  <path d="M6.657 18c-2.572 0 -4.657 -2.007 -4.657 -4.483c0 -2.475 2.085 -4.482 4.657 -4.482c.393 -1.762 1.794 -3.2 3.675 -3.773c1.88 -.572 3.956 -.193 5.444 1c1.488 1.19 2.162 3.007 1.77 4.769h.99c1.913 0 3.464 1.56 3.464 3.486c0 1.927 -1.551 3.487 -3.465 3.487h-11.878" />
</svg>
''',
  'bell': '''<!--
tags: [alarm, sound, notification, bell, control, operation, function, interface, management]
category: System
version: "1.0"
unicode: "ea35"
-->
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
>
  <path d="M10 5a2 2 0 1 1 4 0a7 7 0 0 1 4 6v3a4 4 0 0 0 2 3h-16a4 4 0 0 0 2 -3v-3a7 7 0 0 1 4 -6" />
  <path d="M9 17v1a3 3 0 0 0 6 0v-1" />
</svg>
''',
};
""";
const emptySearchSource =
    r"""import 'package:discourse_native/discourse_ui.dart';
import 'package:discourse_native/src/styleguide/styleguide_chrome.dart';
import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';

class EmptySearchSample extends StatefulWidget {
  const EmptySearchSample({super.key});
  @override
  State<EmptySearchSample> createState() => _EmptySearchSampleState();
}

class _EmptySearchSampleState extends State<EmptySearchSample> {
  final _form = GlobalKey<FormState>();
  String _query = '';
  String? _result;
  void _submit() {
    if (_form.currentState!.validate()) {
      _form.currentState!.save();
      setState(() => _result = 'No local pages match “$_query”.');
    }
  }

  @override
  Widget build(BuildContext context) => Form(
    key: _form,
    child: DEmpty(
      children: [
        const DEmptyHeader(
          children: [
            DEmptyTitle('404 - Not Found'),
            DEmptyDescription(
              "The page you're looking for doesn't exist. Try searching for what you need below.",
            ),
          ],
        ),
        DEmptyContent(
          children: [
            LayoutBuilder(
              builder: (context, constraints) => SizedBox(
                width:
                    constraints.maxWidth *
                    (MediaQuery.sizeOf(context).width >= 640 ? .75 : 1),
                child: TextFormField(
                  decoration: const InputDecoration(
                    hintText: 'Try searching for pages...',
                    labelText: 'Search pages',
                    prefixIcon: Icon(Icons.search),
                    suffixIcon: Padding(
                      padding: EdgeInsets.all(8),
                      child: DKbd('/'),
                    ),
                  ),
                  textInputAction: TextInputAction.search,
                  validator: (value) => value == null || value.trim().isEmpty
                      ? 'Enter a search query.'
                      : null,
                  onSaved: (value) => _query = value!.trim(),
                  onFieldSubmitted: (_) => _submit(),
                ),
              ),
            ),
            StyleguideAction(label: 'Search', onPressed: _submit),
            DEmptyDescription.child(
              child: Wrap(
                alignment: WrapAlignment.center,
                crossAxisAlignment: WrapCrossAlignment.center,
                children: [
                  const Text('Need help?'),
                  StyleguideAction(
                    label: 'Contact support',
                    onPressed: () => setState(
                      () => _result =
                          'Support is available at help@example.test.',
                    ),
                  ),
                ],
              ),
            ),
            if (_result != null)
              Semantics(
                liveRegion: true,
                child: Text(_result!, textAlign: TextAlign.center),
              ),
          ],
        ),
      ],
    ),
  );
}

""";
