// Generated by tool/generate_field_example_sources.dart.
const fieldExampleSources = <String, String>{
  'payment': r'''import 'package:discourse_native/discourse_ui.dart';
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: Scaffold(body: SingleChildScrollView(padding: const EdgeInsets.all(24), child: FieldPaymentExample()))));

class _Editor extends StatefulWidget {
  const _Editor(
    this.label, {
    this.description,
    this.placeholder,
    this.required = false,
    this.lines = 1,
    this.obscure = false,
    this.helpBefore = false,
  });
  final String label;
  final String? description;
  final String? placeholder;
  final bool required;
  final int lines;
  final bool obscure;
  final bool helpBefore;
  @override
  State<_Editor> createState() => _EditorState();
}

class _EditorState extends State<_Editor> {
  final _focus = FocusNode();
  @override
  void dispose() {
    _focus.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => DField(
    children: [
      DFieldLabel(
        focusNode: _focus,
        excludeSemantics: true,
        child: Text(widget.label),
      ),
      if (widget.helpBefore && widget.description != null)
        DFieldDescription(child: Text(widget.description!)),
      DFieldControl(
        label: widget.label,
        description: widget.description,
        required: widget.required,
        child: TextFormField(
          focusNode: _focus,
          maxLines: widget.lines,
          obscureText: widget.obscure,
          decoration: InputDecoration(
            hintText: widget.placeholder,
            errorMaxLines: 4,
            border: const OutlineInputBorder(),
          ),
          validator: widget.required
              ? (value) =>
                    value == null || value.trim().isEmpty ? 'Required' : null
              : null,
        ),
      ),
      if (!widget.helpBefore && widget.description != null)
        DFieldDescription(child: Text(widget.description!)),
    ],
  );
}

class _Choice extends StatefulWidget {
  const _Choice(
    this.label, {
    this.description,
    this.initial = false,
    this.enabled = true,
    this.switchControl = false,
  });
  final String label;
  final String? description;
  final bool initial;
  final bool enabled;
  final bool switchControl;
  @override
  State<_Choice> createState() => _ChoiceState();
}

class _ChoiceState extends State<_Choice> {
  late bool _value = widget.initial;
  void _change(bool value) => setState(() => _value = value);
  @override
  Widget build(BuildContext context) => DField(
    enabled: widget.enabled,
    orientation: DFieldOrientation.horizontal,
    children: [
      DFieldControl(
        label: widget.label,
        description: widget.description,
        expand: false,
        alignIndicatorToContent: !widget.switchControl,
        child: widget.switchControl
            ? Switch(value: _value, onChanged: widget.enabled ? _change : null)
            : Checkbox(
                value: _value,
                onChanged: widget.enabled
                    ? (value) => _change(value ?? false)
                    : null,
              ),
      ),
      DFieldContent(
        children: [
          DFieldLabel(
            excludeSemantics: true,
            onPressed: () => _change(!_value),
            style: const TextStyle(fontWeight: FontWeight.w400),
            child: Text(widget.label),
          ),
          if (widget.description != null)
            DFieldDescription(child: Text(widget.description!)),
        ],
      ),
    ],
  );
}

class _Selection extends StatefulWidget {
  const _Selection(this.label, this.items, {this.description});
  final String label;
  final List<String> items;
  final String? description;
  @override
  State<_Selection> createState() => _SelectionState();
}

class _SelectionState extends State<_Selection> {
  final _focus = FocusNode();
  String? _value;
  @override
  void dispose() {
    _focus.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => DField(
    children: [
      DFieldLabel(
        focusNode: _focus,
        excludeSemantics: true,
        child: Text(widget.label),
      ),
      DFieldControl(
        label: widget.label,
        description: widget.description,
        child: DropdownButtonFormField<String>(
          focusNode: _focus,
          initialValue: _value,
          isExpanded: true,
          hint: const Text('Choose'),
          items: [
            for (final item in widget.items)
              DropdownMenuItem(value: item, child: Text(item)),
          ],
          onChanged: (value) => setState(() => _value = value),
        ),
      ),
      if (widget.description != null)
        DFieldDescription(child: Text(widget.description!)),
    ],
  );
}

class _Columns extends StatelessWidget {
  const _Columns({required this.children});
  final List<Widget> children;
  @override
  Widget build(BuildContext context) => LayoutBuilder(
    builder: (context, constraints) {
      final horizontal =
          constraints.maxWidth >= 360 &&
          MediaQuery.textScalerOf(context).scale(14) <= 21;
      return Flex(
        direction: horizontal ? Axis.horizontal : Axis.vertical,
        crossAxisAlignment: CrossAxisAlignment.start,
        mainAxisSize: MainAxisSize.min,
        children: [
          for (var i = 0; i < children.length; i++) ...[
            if (i > 0)
              SizedBox(width: horizontal ? 16 : 0, height: horizontal ? 0 : 16),
            Flexible(flex: horizontal ? 1 : 0, child: children[i]),
          ],
        ],
      );
    },
  );
}

class FieldPaymentExample extends StatefulWidget {
  const FieldPaymentExample({super.key, this.arabic = false});
  final bool arabic;
  @override
  State<FieldPaymentExample> createState() => _FieldPaymentExampleState();
}

class _FieldPaymentExampleState extends State<FieldPaymentExample> {
  final _form = GlobalKey<FormState>();
  int _reset = 0;
  String? _saved;
  @override
  Widget build(BuildContext context) {
    final ar = widget.arabic;
    return Form(
      key: _form,
      child: DFieldGroup(
        children: [
          DFieldSet(
            children: [
              DFieldLegend(child: Text(ar ? 'طريقة الدفع' : 'Payment Method')),
              DFieldDescription(
                child: Text(
                  ar
                      ? 'جميع المعاملات آمنة ومشفرة'
                      : 'All transactions are secure and encrypted',
                ),
              ),
              DFieldGroup(
                children: [
                  _Editor(
                    ar ? 'الاسم على البطاقة' : 'Name on Card',
                    placeholder: 'Evil Rabbit',
                    required: true,
                  ),
                  _Editor(
                    ar ? 'رقم البطاقة' : 'Card Number',
                    placeholder: '1234 5678 9012 3456',
                    required: true,
                    description: ar
                        ? 'أدخل رقم البطاقة المكون من 16 رقمًا'
                        : 'Enter your 16-digit card number',
                  ),
                  _Columns(
                    children: [
                      _Selection(ar ? 'الشهر' : 'Month', const [
                        '01',
                        '02',
                        '03',
                        '04',
                        '05',
                        '06',
                        '07',
                        '08',
                        '09',
                        '10',
                        '11',
                        '12',
                      ]),
                      _Selection(ar ? 'السنة' : 'Year', const [
                        '2024',
                        '2025',
                        '2026',
                        '2027',
                        '2028',
                        '2029',
                      ]),
                      const _Editor('CVV', placeholder: '123', required: true),
                    ],
                  ),
                ],
              ),
            ],
          ),
          const DFieldSeparator(),
          DFieldSet(
            children: [
              DFieldLegend(
                child: Text(ar ? 'عنوان الفوترة' : 'Billing Address'),
              ),
              DFieldDescription(
                child: Text(
                  ar
                      ? 'عنوان الفوترة المرتبط بطريقة الدفع الخاصة بك'
                      : 'The billing address associated with your payment method',
                ),
              ),
              KeyedSubtree(
                key: ValueKey(_reset),
                child: _Choice(
                  ar ? 'نفس عنوان الشحن' : 'Same as shipping address',
                  initial: true,
                ),
              ),
            ],
          ),
          _Editor(
            ar ? 'تعليقات' : 'Comments',
            lines: 3,
            placeholder: ar
                ? 'أضف أي تعليقات إضافية'
                : 'Add any additional comments',
          ),
          Wrap(
            spacing: 8,
            runSpacing: 8,
            children: [
              DButton(
                label: Text(ar ? 'إرسال' : 'Submit'),
                onPressed: () {
                  if (_form.currentState!.validate()) {
                    setState(
                      () => _saved = ar ? 'تم الحفظ محليًا' : 'Saved locally',
                    );
                  }
                },
              ),
              DButton(
                label: Text(ar ? 'إلغاء' : 'Cancel'),
                onPressed: () {
                  _form.currentState!.reset();
                  setState(() {
                    _reset++;
                    _saved = null;
                  });
                },
              ),
            ],
          ),
          if (_saved != null) Semantics(liveRegion: true, child: Text(_saved!)),
        ],
      ),
    );
  }
}

''',
  'editors': r'''import 'package:discourse_native/discourse_ui.dart';
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: Scaffold(body: SingleChildScrollView(padding: const EdgeInsets.all(24), child: FieldEditorsExample()))));

class _Editor extends StatefulWidget {
  const _Editor(
    this.label, {
    this.description,
    this.placeholder,
    this.required = false,
    this.lines = 1,
    this.obscure = false,
    this.helpBefore = false,
  });
  final String label;
  final String? description;
  final String? placeholder;
  final bool required;
  final int lines;
  final bool obscure;
  final bool helpBefore;
  @override
  State<_Editor> createState() => _EditorState();
}

class _EditorState extends State<_Editor> {
  final _focus = FocusNode();
  @override
  void dispose() {
    _focus.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => DField(
    children: [
      DFieldLabel(
        focusNode: _focus,
        excludeSemantics: true,
        child: Text(widget.label),
      ),
      if (widget.helpBefore && widget.description != null)
        DFieldDescription(child: Text(widget.description!)),
      DFieldControl(
        label: widget.label,
        description: widget.description,
        required: widget.required,
        child: TextFormField(
          focusNode: _focus,
          maxLines: widget.lines,
          obscureText: widget.obscure,
          decoration: InputDecoration(
            hintText: widget.placeholder,
            errorMaxLines: 4,
            border: const OutlineInputBorder(),
          ),
          validator: widget.required
              ? (value) =>
                    value == null || value.trim().isEmpty ? 'Required' : null
              : null,
        ),
      ),
      if (!widget.helpBefore && widget.description != null)
        DFieldDescription(child: Text(widget.description!)),
    ],
  );
}

class _Choice extends StatefulWidget {
  const _Choice(
    this.label, {
    this.description,
    this.initial = false,
    this.enabled = true,
    this.switchControl = false,
  });
  final String label;
  final String? description;
  final bool initial;
  final bool enabled;
  final bool switchControl;
  @override
  State<_Choice> createState() => _ChoiceState();
}

class _ChoiceState extends State<_Choice> {
  late bool _value = widget.initial;
  void _change(bool value) => setState(() => _value = value);
  @override
  Widget build(BuildContext context) => DField(
    enabled: widget.enabled,
    orientation: DFieldOrientation.horizontal,
    children: [
      DFieldControl(
        label: widget.label,
        description: widget.description,
        expand: false,
        alignIndicatorToContent: !widget.switchControl,
        child: widget.switchControl
            ? Switch(value: _value, onChanged: widget.enabled ? _change : null)
            : Checkbox(
                value: _value,
                onChanged: widget.enabled
                    ? (value) => _change(value ?? false)
                    : null,
              ),
      ),
      DFieldContent(
        children: [
          DFieldLabel(
            excludeSemantics: true,
            onPressed: () => _change(!_value),
            style: const TextStyle(fontWeight: FontWeight.w400),
            child: Text(widget.label),
          ),
          if (widget.description != null)
            DFieldDescription(child: Text(widget.description!)),
        ],
      ),
    ],
  );
}

class _Selection extends StatefulWidget {
  const _Selection(this.label, this.items, {this.description});
  final String label;
  final List<String> items;
  final String? description;
  @override
  State<_Selection> createState() => _SelectionState();
}

class _SelectionState extends State<_Selection> {
  final _focus = FocusNode();
  String? _value;
  @override
  void dispose() {
    _focus.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => DField(
    children: [
      DFieldLabel(
        focusNode: _focus,
        excludeSemantics: true,
        child: Text(widget.label),
      ),
      DFieldControl(
        label: widget.label,
        description: widget.description,
        child: DropdownButtonFormField<String>(
          focusNode: _focus,
          initialValue: _value,
          isExpanded: true,
          hint: const Text('Choose'),
          items: [
            for (final item in widget.items)
              DropdownMenuItem(value: item, child: Text(item)),
          ],
          onChanged: (value) => setState(() => _value = value),
        ),
      ),
      if (widget.description != null)
        DFieldDescription(child: Text(widget.description!)),
    ],
  );
}

class _Columns extends StatelessWidget {
  const _Columns({required this.children});
  final List<Widget> children;
  @override
  Widget build(BuildContext context) => LayoutBuilder(
    builder: (context, constraints) {
      final horizontal =
          constraints.maxWidth >= 360 &&
          MediaQuery.textScalerOf(context).scale(14) <= 21;
      return Flex(
        direction: horizontal ? Axis.horizontal : Axis.vertical,
        crossAxisAlignment: CrossAxisAlignment.start,
        mainAxisSize: MainAxisSize.min,
        children: [
          for (var i = 0; i < children.length; i++) ...[
            if (i > 0)
              SizedBox(width: horizontal ? 16 : 0, height: horizontal ? 0 : 16),
            Flexible(flex: horizontal ? 1 : 0, child: children[i]),
          ],
        ],
      );
    },
  );
}

class FieldEditorsExample extends StatelessWidget {
  const FieldEditorsExample({super.key});
  @override
  Widget build(BuildContext context) => const DFieldSet(
    children: [
      DFieldGroup(
        children: [
          _Editor(
            'Username',
            placeholder: 'Max Leiter',
            description: 'Choose a unique username for your account.',
          ),
          _Editor(
            'Password',
            obscure: true,
            placeholder: '••••••••',
            helpBefore: true,
            description: 'Must be at least 8 characters long.',
          ),
          _Editor(
            'Feedback',
            lines: 4,
            placeholder: 'Your feedback helps us improve...',
            description: 'Share your thoughts about our service.',
          ),
          _Selection('Department', [
            'Engineering',
            'Design',
            'Marketing',
            'Sales',
            'Customer Support',
            'Human Resources',
            'Finance',
            'Operations',
          ], description: 'Select your department or area of work.'),
        ],
      ),
    ],
  );
}

''',
  'slider': r'''import 'package:discourse_native/discourse_ui.dart';
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: Scaffold(body: SingleChildScrollView(padding: const EdgeInsets.all(24), child: FieldSliderExample()))));

class _Editor extends StatefulWidget {
  const _Editor(
    this.label, {
    this.description,
    this.placeholder,
    this.required = false,
    this.lines = 1,
    this.obscure = false,
    this.helpBefore = false,
  });
  final String label;
  final String? description;
  final String? placeholder;
  final bool required;
  final int lines;
  final bool obscure;
  final bool helpBefore;
  @override
  State<_Editor> createState() => _EditorState();
}

class _EditorState extends State<_Editor> {
  final _focus = FocusNode();
  @override
  void dispose() {
    _focus.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => DField(
    children: [
      DFieldLabel(
        focusNode: _focus,
        excludeSemantics: true,
        child: Text(widget.label),
      ),
      if (widget.helpBefore && widget.description != null)
        DFieldDescription(child: Text(widget.description!)),
      DFieldControl(
        label: widget.label,
        description: widget.description,
        required: widget.required,
        child: TextFormField(
          focusNode: _focus,
          maxLines: widget.lines,
          obscureText: widget.obscure,
          decoration: InputDecoration(
            hintText: widget.placeholder,
            errorMaxLines: 4,
            border: const OutlineInputBorder(),
          ),
          validator: widget.required
              ? (value) =>
                    value == null || value.trim().isEmpty ? 'Required' : null
              : null,
        ),
      ),
      if (!widget.helpBefore && widget.description != null)
        DFieldDescription(child: Text(widget.description!)),
    ],
  );
}

class _Choice extends StatefulWidget {
  const _Choice(
    this.label, {
    this.description,
    this.initial = false,
    this.enabled = true,
    this.switchControl = false,
  });
  final String label;
  final String? description;
  final bool initial;
  final bool enabled;
  final bool switchControl;
  @override
  State<_Choice> createState() => _ChoiceState();
}

class _ChoiceState extends State<_Choice> {
  late bool _value = widget.initial;
  void _change(bool value) => setState(() => _value = value);
  @override
  Widget build(BuildContext context) => DField(
    enabled: widget.enabled,
    orientation: DFieldOrientation.horizontal,
    children: [
      DFieldControl(
        label: widget.label,
        description: widget.description,
        expand: false,
        alignIndicatorToContent: !widget.switchControl,
        child: widget.switchControl
            ? Switch(value: _value, onChanged: widget.enabled ? _change : null)
            : Checkbox(
                value: _value,
                onChanged: widget.enabled
                    ? (value) => _change(value ?? false)
                    : null,
              ),
      ),
      DFieldContent(
        children: [
          DFieldLabel(
            excludeSemantics: true,
            onPressed: () => _change(!_value),
            style: const TextStyle(fontWeight: FontWeight.w400),
            child: Text(widget.label),
          ),
          if (widget.description != null)
            DFieldDescription(child: Text(widget.description!)),
        ],
      ),
    ],
  );
}

class _Selection extends StatefulWidget {
  const _Selection(this.label, this.items, {this.description});
  final String label;
  final List<String> items;
  final String? description;
  @override
  State<_Selection> createState() => _SelectionState();
}

class _SelectionState extends State<_Selection> {
  final _focus = FocusNode();
  String? _value;
  @override
  void dispose() {
    _focus.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => DField(
    children: [
      DFieldLabel(
        focusNode: _focus,
        excludeSemantics: true,
        child: Text(widget.label),
      ),
      DFieldControl(
        label: widget.label,
        description: widget.description,
        child: DropdownButtonFormField<String>(
          focusNode: _focus,
          initialValue: _value,
          isExpanded: true,
          hint: const Text('Choose'),
          items: [
            for (final item in widget.items)
              DropdownMenuItem(value: item, child: Text(item)),
          ],
          onChanged: (value) => setState(() => _value = value),
        ),
      ),
      if (widget.description != null)
        DFieldDescription(child: Text(widget.description!)),
    ],
  );
}

class _Columns extends StatelessWidget {
  const _Columns({required this.children});
  final List<Widget> children;
  @override
  Widget build(BuildContext context) => LayoutBuilder(
    builder: (context, constraints) {
      final horizontal =
          constraints.maxWidth >= 360 &&
          MediaQuery.textScalerOf(context).scale(14) <= 21;
      return Flex(
        direction: horizontal ? Axis.horizontal : Axis.vertical,
        crossAxisAlignment: CrossAxisAlignment.start,
        mainAxisSize: MainAxisSize.min,
        children: [
          for (var i = 0; i < children.length; i++) ...[
            if (i > 0)
              SizedBox(width: horizontal ? 16 : 0, height: horizontal ? 0 : 16),
            Flexible(flex: horizontal ? 1 : 0, child: children[i]),
          ],
        ],
      );
    },
  );
}

class FieldSliderExample extends StatefulWidget {
  const FieldSliderExample({super.key});
  @override
  State<FieldSliderExample> createState() => _FieldSliderExampleState();
}

class _FieldSliderExampleState extends State<FieldSliderExample> {
  RangeValues _range = const RangeValues(200, 800);
  @override
  Widget build(BuildContext context) => DField(
    children: [
      const DFieldTitle(child: Text('Price Range')),
      DFieldDescription(
        child: Text(
          'Set your budget range (\$${_range.start.round()} - \$${_range.end.round()}).',
        ),
      ),
      RangeSlider(
        values: _range,
        max: 1000,
        divisions: 100,
        semanticFormatterCallback: (value) => 'Price Range: \$${value.round()}',
        onChanged: (value) => setState(() => _range = value),
      ),
    ],
  );
}

''',
  'address': r'''import 'package:discourse_native/discourse_ui.dart';
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: Scaffold(body: SingleChildScrollView(padding: const EdgeInsets.all(24), child: FieldAddressExample()))));

class _Editor extends StatefulWidget {
  const _Editor(
    this.label, {
    this.description,
    this.placeholder,
    this.required = false,
    this.lines = 1,
    this.obscure = false,
    this.helpBefore = false,
  });
  final String label;
  final String? description;
  final String? placeholder;
  final bool required;
  final int lines;
  final bool obscure;
  final bool helpBefore;
  @override
  State<_Editor> createState() => _EditorState();
}

class _EditorState extends State<_Editor> {
  final _focus = FocusNode();
  @override
  void dispose() {
    _focus.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => DField(
    children: [
      DFieldLabel(
        focusNode: _focus,
        excludeSemantics: true,
        child: Text(widget.label),
      ),
      if (widget.helpBefore && widget.description != null)
        DFieldDescription(child: Text(widget.description!)),
      DFieldControl(
        label: widget.label,
        description: widget.description,
        required: widget.required,
        child: TextFormField(
          focusNode: _focus,
          maxLines: widget.lines,
          obscureText: widget.obscure,
          decoration: InputDecoration(
            hintText: widget.placeholder,
            errorMaxLines: 4,
            border: const OutlineInputBorder(),
          ),
          validator: widget.required
              ? (value) =>
                    value == null || value.trim().isEmpty ? 'Required' : null
              : null,
        ),
      ),
      if (!widget.helpBefore && widget.description != null)
        DFieldDescription(child: Text(widget.description!)),
    ],
  );
}

class _Choice extends StatefulWidget {
  const _Choice(
    this.label, {
    this.description,
    this.initial = false,
    this.enabled = true,
    this.switchControl = false,
  });
  final String label;
  final String? description;
  final bool initial;
  final bool enabled;
  final bool switchControl;
  @override
  State<_Choice> createState() => _ChoiceState();
}

class _ChoiceState extends State<_Choice> {
  late bool _value = widget.initial;
  void _change(bool value) => setState(() => _value = value);
  @override
  Widget build(BuildContext context) => DField(
    enabled: widget.enabled,
    orientation: DFieldOrientation.horizontal,
    children: [
      DFieldControl(
        label: widget.label,
        description: widget.description,
        expand: false,
        alignIndicatorToContent: !widget.switchControl,
        child: widget.switchControl
            ? Switch(value: _value, onChanged: widget.enabled ? _change : null)
            : Checkbox(
                value: _value,
                onChanged: widget.enabled
                    ? (value) => _change(value ?? false)
                    : null,
              ),
      ),
      DFieldContent(
        children: [
          DFieldLabel(
            excludeSemantics: true,
            onPressed: () => _change(!_value),
            style: const TextStyle(fontWeight: FontWeight.w400),
            child: Text(widget.label),
          ),
          if (widget.description != null)
            DFieldDescription(child: Text(widget.description!)),
        ],
      ),
    ],
  );
}

class _Selection extends StatefulWidget {
  const _Selection(this.label, this.items, {this.description});
  final String label;
  final List<String> items;
  final String? description;
  @override
  State<_Selection> createState() => _SelectionState();
}

class _SelectionState extends State<_Selection> {
  final _focus = FocusNode();
  String? _value;
  @override
  void dispose() {
    _focus.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => DField(
    children: [
      DFieldLabel(
        focusNode: _focus,
        excludeSemantics: true,
        child: Text(widget.label),
      ),
      DFieldControl(
        label: widget.label,
        description: widget.description,
        child: DropdownButtonFormField<String>(
          focusNode: _focus,
          initialValue: _value,
          isExpanded: true,
          hint: const Text('Choose'),
          items: [
            for (final item in widget.items)
              DropdownMenuItem(value: item, child: Text(item)),
          ],
          onChanged: (value) => setState(() => _value = value),
        ),
      ),
      if (widget.description != null)
        DFieldDescription(child: Text(widget.description!)),
    ],
  );
}

class _Columns extends StatelessWidget {
  const _Columns({required this.children});
  final List<Widget> children;
  @override
  Widget build(BuildContext context) => LayoutBuilder(
    builder: (context, constraints) {
      final horizontal =
          constraints.maxWidth >= 360 &&
          MediaQuery.textScalerOf(context).scale(14) <= 21;
      return Flex(
        direction: horizontal ? Axis.horizontal : Axis.vertical,
        crossAxisAlignment: CrossAxisAlignment.start,
        mainAxisSize: MainAxisSize.min,
        children: [
          for (var i = 0; i < children.length; i++) ...[
            if (i > 0)
              SizedBox(width: horizontal ? 16 : 0, height: horizontal ? 0 : 16),
            Flexible(flex: horizontal ? 1 : 0, child: children[i]),
          ],
        ],
      );
    },
  );
}

class FieldAddressExample extends StatelessWidget {
  const FieldAddressExample({super.key});
  @override
  Widget build(BuildContext context) => const DFieldSet(
    children: [
      DFieldLegend(child: Text('Address Information')),
      DFieldDescription(
        child: Text('We need your address to deliver your order.'),
      ),
      DFieldGroup(
        children: [
          _Editor('Street Address', placeholder: '123 Main St'),
          _Columns(
            children: [
              _Editor('City', placeholder: 'New York'),
              _Editor('Postal Code', placeholder: '90502'),
            ],
          ),
        ],
      ),
    ],
  );
}

''',
  'checkbox': r'''import 'package:discourse_native/discourse_ui.dart';
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: Scaffold(body: SingleChildScrollView(padding: const EdgeInsets.all(24), child: FieldCheckboxExample()))));

class _Editor extends StatefulWidget {
  const _Editor(
    this.label, {
    this.description,
    this.placeholder,
    this.required = false,
    this.lines = 1,
    this.obscure = false,
    this.helpBefore = false,
  });
  final String label;
  final String? description;
  final String? placeholder;
  final bool required;
  final int lines;
  final bool obscure;
  final bool helpBefore;
  @override
  State<_Editor> createState() => _EditorState();
}

class _EditorState extends State<_Editor> {
  final _focus = FocusNode();
  @override
  void dispose() {
    _focus.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => DField(
    children: [
      DFieldLabel(
        focusNode: _focus,
        excludeSemantics: true,
        child: Text(widget.label),
      ),
      if (widget.helpBefore && widget.description != null)
        DFieldDescription(child: Text(widget.description!)),
      DFieldControl(
        label: widget.label,
        description: widget.description,
        required: widget.required,
        child: TextFormField(
          focusNode: _focus,
          maxLines: widget.lines,
          obscureText: widget.obscure,
          decoration: InputDecoration(
            hintText: widget.placeholder,
            errorMaxLines: 4,
            border: const OutlineInputBorder(),
          ),
          validator: widget.required
              ? (value) =>
                    value == null || value.trim().isEmpty ? 'Required' : null
              : null,
        ),
      ),
      if (!widget.helpBefore && widget.description != null)
        DFieldDescription(child: Text(widget.description!)),
    ],
  );
}

class _Choice extends StatefulWidget {
  const _Choice(
    this.label, {
    this.description,
    this.initial = false,
    this.enabled = true,
    this.switchControl = false,
  });
  final String label;
  final String? description;
  final bool initial;
  final bool enabled;
  final bool switchControl;
  @override
  State<_Choice> createState() => _ChoiceState();
}

class _ChoiceState extends State<_Choice> {
  late bool _value = widget.initial;
  void _change(bool value) => setState(() => _value = value);
  @override
  Widget build(BuildContext context) => DField(
    enabled: widget.enabled,
    orientation: DFieldOrientation.horizontal,
    children: [
      DFieldControl(
        label: widget.label,
        description: widget.description,
        expand: false,
        alignIndicatorToContent: !widget.switchControl,
        child: widget.switchControl
            ? Switch(value: _value, onChanged: widget.enabled ? _change : null)
            : Checkbox(
                value: _value,
                onChanged: widget.enabled
                    ? (value) => _change(value ?? false)
                    : null,
              ),
      ),
      DFieldContent(
        children: [
          DFieldLabel(
            excludeSemantics: true,
            onPressed: () => _change(!_value),
            style: const TextStyle(fontWeight: FontWeight.w400),
            child: Text(widget.label),
          ),
          if (widget.description != null)
            DFieldDescription(child: Text(widget.description!)),
        ],
      ),
    ],
  );
}

class _Selection extends StatefulWidget {
  const _Selection(this.label, this.items, {this.description});
  final String label;
  final List<String> items;
  final String? description;
  @override
  State<_Selection> createState() => _SelectionState();
}

class _SelectionState extends State<_Selection> {
  final _focus = FocusNode();
  String? _value;
  @override
  void dispose() {
    _focus.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => DField(
    children: [
      DFieldLabel(
        focusNode: _focus,
        excludeSemantics: true,
        child: Text(widget.label),
      ),
      DFieldControl(
        label: widget.label,
        description: widget.description,
        child: DropdownButtonFormField<String>(
          focusNode: _focus,
          initialValue: _value,
          isExpanded: true,
          hint: const Text('Choose'),
          items: [
            for (final item in widget.items)
              DropdownMenuItem(value: item, child: Text(item)),
          ],
          onChanged: (value) => setState(() => _value = value),
        ),
      ),
      if (widget.description != null)
        DFieldDescription(child: Text(widget.description!)),
    ],
  );
}

class _Columns extends StatelessWidget {
  const _Columns({required this.children});
  final List<Widget> children;
  @override
  Widget build(BuildContext context) => LayoutBuilder(
    builder: (context, constraints) {
      final horizontal =
          constraints.maxWidth >= 360 &&
          MediaQuery.textScalerOf(context).scale(14) <= 21;
      return Flex(
        direction: horizontal ? Axis.horizontal : Axis.vertical,
        crossAxisAlignment: CrossAxisAlignment.start,
        mainAxisSize: MainAxisSize.min,
        children: [
          for (var i = 0; i < children.length; i++) ...[
            if (i > 0)
              SizedBox(width: horizontal ? 16 : 0, height: horizontal ? 0 : 16),
            Flexible(flex: horizontal ? 1 : 0, child: children[i]),
          ],
        ],
      );
    },
  );
}

class FieldCheckboxExample extends StatelessWidget {
  const FieldCheckboxExample({super.key});
  @override
  Widget build(BuildContext context) => const DFieldGroup(
    children: [
      DFieldSet(
        children: [
          DFieldLegend(
            variant: DFieldLegendVariant.label,
            child: Text('Show these items on the desktop'),
          ),
          DFieldDescription(
            child: Text('Select the items you want to show on the desktop.'),
          ),
          DFieldGroup(
            variant: DFieldGroupVariant.choice,
            children: [
              _Choice('Hard disks'),
              _Choice('External disks'),
              _Choice('CDs, DVDs, and iPods'),
              _Choice('Connected servers'),
            ],
          ),
        ],
      ),
      DFieldSeparator(),
      _Choice(
        'Sync Desktop & Documents folders',
        initial: true,
        description:
            'Your Desktop & Documents folders are being synced with iCloud Drive. You can access them from other devices.',
      ),
    ],
  );
}

''',
  'choice': r'''import 'package:discourse_native/discourse_ui.dart';
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: Scaffold(body: SingleChildScrollView(padding: const EdgeInsets.all(24), child: FieldChoiceExample()))));

class _Editor extends StatefulWidget {
  const _Editor(
    this.label, {
    this.description,
    this.placeholder,
    this.required = false,
    this.lines = 1,
    this.obscure = false,
    this.helpBefore = false,
  });
  final String label;
  final String? description;
  final String? placeholder;
  final bool required;
  final int lines;
  final bool obscure;
  final bool helpBefore;
  @override
  State<_Editor> createState() => _EditorState();
}

class _EditorState extends State<_Editor> {
  final _focus = FocusNode();
  @override
  void dispose() {
    _focus.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => DField(
    children: [
      DFieldLabel(
        focusNode: _focus,
        excludeSemantics: true,
        child: Text(widget.label),
      ),
      if (widget.helpBefore && widget.description != null)
        DFieldDescription(child: Text(widget.description!)),
      DFieldControl(
        label: widget.label,
        description: widget.description,
        required: widget.required,
        child: TextFormField(
          focusNode: _focus,
          maxLines: widget.lines,
          obscureText: widget.obscure,
          decoration: InputDecoration(
            hintText: widget.placeholder,
            errorMaxLines: 4,
            border: const OutlineInputBorder(),
          ),
          validator: widget.required
              ? (value) =>
                    value == null || value.trim().isEmpty ? 'Required' : null
              : null,
        ),
      ),
      if (!widget.helpBefore && widget.description != null)
        DFieldDescription(child: Text(widget.description!)),
    ],
  );
}

class _Choice extends StatefulWidget {
  const _Choice(
    this.label, {
    this.description,
    this.initial = false,
    this.enabled = true,
    this.switchControl = false,
  });
  final String label;
  final String? description;
  final bool initial;
  final bool enabled;
  final bool switchControl;
  @override
  State<_Choice> createState() => _ChoiceState();
}

class _ChoiceState extends State<_Choice> {
  late bool _value = widget.initial;
  void _change(bool value) => setState(() => _value = value);
  @override
  Widget build(BuildContext context) => DField(
    enabled: widget.enabled,
    orientation: DFieldOrientation.horizontal,
    children: [
      DFieldControl(
        label: widget.label,
        description: widget.description,
        expand: false,
        alignIndicatorToContent: !widget.switchControl,
        child: widget.switchControl
            ? Switch(value: _value, onChanged: widget.enabled ? _change : null)
            : Checkbox(
                value: _value,
                onChanged: widget.enabled
                    ? (value) => _change(value ?? false)
                    : null,
              ),
      ),
      DFieldContent(
        children: [
          DFieldLabel(
            excludeSemantics: true,
            onPressed: () => _change(!_value),
            style: const TextStyle(fontWeight: FontWeight.w400),
            child: Text(widget.label),
          ),
          if (widget.description != null)
            DFieldDescription(child: Text(widget.description!)),
        ],
      ),
    ],
  );
}

class _Selection extends StatefulWidget {
  const _Selection(this.label, this.items, {this.description});
  final String label;
  final List<String> items;
  final String? description;
  @override
  State<_Selection> createState() => _SelectionState();
}

class _SelectionState extends State<_Selection> {
  final _focus = FocusNode();
  String? _value;
  @override
  void dispose() {
    _focus.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => DField(
    children: [
      DFieldLabel(
        focusNode: _focus,
        excludeSemantics: true,
        child: Text(widget.label),
      ),
      DFieldControl(
        label: widget.label,
        description: widget.description,
        child: DropdownButtonFormField<String>(
          focusNode: _focus,
          initialValue: _value,
          isExpanded: true,
          hint: const Text('Choose'),
          items: [
            for (final item in widget.items)
              DropdownMenuItem(value: item, child: Text(item)),
          ],
          onChanged: (value) => setState(() => _value = value),
        ),
      ),
      if (widget.description != null)
        DFieldDescription(child: Text(widget.description!)),
    ],
  );
}

class _Columns extends StatelessWidget {
  const _Columns({required this.children});
  final List<Widget> children;
  @override
  Widget build(BuildContext context) => LayoutBuilder(
    builder: (context, constraints) {
      final horizontal =
          constraints.maxWidth >= 360 &&
          MediaQuery.textScalerOf(context).scale(14) <= 21;
      return Flex(
        direction: horizontal ? Axis.horizontal : Axis.vertical,
        crossAxisAlignment: CrossAxisAlignment.start,
        mainAxisSize: MainAxisSize.min,
        children: [
          for (var i = 0; i < children.length; i++) ...[
            if (i > 0)
              SizedBox(width: horizontal ? 16 : 0, height: horizontal ? 0 : 16),
            Flexible(flex: horizontal ? 1 : 0, child: children[i]),
          ],
        ],
      );
    },
  );
}

class FieldChoiceExample extends StatefulWidget {
  const FieldChoiceExample({super.key});
  @override
  State<FieldChoiceExample> createState() => _FieldChoiceExampleState();
}

class _FieldChoiceExampleState extends State<FieldChoiceExample> {
  String _plan = 'Monthly (\$9.99/month)';
  String _compute = 'Kubernetes';
  @override
  Widget build(BuildContext context) => DFieldGroup(
    children: [
      DFieldSet(
        children: [
          const DFieldLegend(
            variant: DFieldLegendVariant.label,
            child: Text('Subscription Plan'),
          ),
          const DFieldDescription(
            child: Text('Yearly and lifetime plans offer significant savings.'),
          ),
          RadioGroup<String>(
            groupValue: _plan,
            onChanged: (value) => setState(() => _plan = value!),
            child: DFieldGroup(
              variant: DFieldGroupVariant.choice,
              children: [
                for (final plan in [
                  'Monthly (\$9.99/month)',
                  'Yearly (\$99.99/year)',
                  'Lifetime (\$299.99)',
                ])
                  DField(
                    orientation: DFieldOrientation.horizontal,
                    children: [
                      DFieldControl(
                        label: plan,
                        expand: false,
                        alignIndicatorToContent: true,
                        child: Radio<String>(value: plan),
                      ),
                      DFieldLabel(
                        excludeSemantics: true,
                        onPressed: () => setState(() => _plan = plan),
                        style: const TextStyle(fontWeight: FontWeight.w400),
                        child: Text(plan),
                      ),
                    ],
                  ),
              ],
            ),
          ),
        ],
      ),
      DFieldSet(
        children: [
          const DFieldLegend(
            variant: DFieldLegendVariant.label,
            child: Text('Compute Environment'),
          ),
          const DFieldDescription(
            child: Text('Select the compute environment for your cluster.'),
          ),
          RadioGroup<String>(
            groupValue: _compute,
            onChanged: (value) => setState(() => _compute = value!),
            child: DFieldGroup(
              variant: DFieldGroupVariant.choice,
              children: [
                for (final name in [
                  'Kubernetes',
                  'Virtual Machine',
                  'Unavailable environment',
                ])
                  DFieldLabel.choice(
                    selected: _compute == name,
                    enabled: name != 'Unavailable environment',
                    onPressed: () => setState(() => _compute = name),
                    child: DField(
                      orientation: DFieldOrientation.horizontal,
                      children: [
                        DFieldContent(
                          children: [
                            DFieldTitle(
                              excludeSemantics: true,
                              child: Text(name),
                            ),
                            DFieldDescription(
                              child: Text(
                                name == 'Kubernetes'
                                    ? 'Run GPU workloads on a K8s cluster.'
                                    : 'Access a cluster to run GPU workloads.',
                              ),
                            ),
                          ],
                        ),
                        DFieldControl(
                          label: name,
                          expand: false,
                          alignIndicatorToContent: true,
                          child: Radio<String>(
                            value: name,
                            enabled: name != 'Unavailable environment',
                          ),
                        ),
                      ],
                    ),
                  ),
              ],
            ),
          ),
        ],
      ),
    ],
  );
}

''',
  'notifications': r'''import 'package:discourse_native/discourse_ui.dart';
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: Scaffold(body: SingleChildScrollView(padding: const EdgeInsets.all(24), child: FieldNotificationsExample()))));

class _Editor extends StatefulWidget {
  const _Editor(
    this.label, {
    this.description,
    this.placeholder,
    this.required = false,
    this.lines = 1,
    this.obscure = false,
    this.helpBefore = false,
  });
  final String label;
  final String? description;
  final String? placeholder;
  final bool required;
  final int lines;
  final bool obscure;
  final bool helpBefore;
  @override
  State<_Editor> createState() => _EditorState();
}

class _EditorState extends State<_Editor> {
  final _focus = FocusNode();
  @override
  void dispose() {
    _focus.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => DField(
    children: [
      DFieldLabel(
        focusNode: _focus,
        excludeSemantics: true,
        child: Text(widget.label),
      ),
      if (widget.helpBefore && widget.description != null)
        DFieldDescription(child: Text(widget.description!)),
      DFieldControl(
        label: widget.label,
        description: widget.description,
        required: widget.required,
        child: TextFormField(
          focusNode: _focus,
          maxLines: widget.lines,
          obscureText: widget.obscure,
          decoration: InputDecoration(
            hintText: widget.placeholder,
            errorMaxLines: 4,
            border: const OutlineInputBorder(),
          ),
          validator: widget.required
              ? (value) =>
                    value == null || value.trim().isEmpty ? 'Required' : null
              : null,
        ),
      ),
      if (!widget.helpBefore && widget.description != null)
        DFieldDescription(child: Text(widget.description!)),
    ],
  );
}

class _Choice extends StatefulWidget {
  const _Choice(
    this.label, {
    this.description,
    this.initial = false,
    this.enabled = true,
    this.switchControl = false,
  });
  final String label;
  final String? description;
  final bool initial;
  final bool enabled;
  final bool switchControl;
  @override
  State<_Choice> createState() => _ChoiceState();
}

class _ChoiceState extends State<_Choice> {
  late bool _value = widget.initial;
  void _change(bool value) => setState(() => _value = value);
  @override
  Widget build(BuildContext context) => DField(
    enabled: widget.enabled,
    orientation: DFieldOrientation.horizontal,
    children: [
      DFieldControl(
        label: widget.label,
        description: widget.description,
        expand: false,
        alignIndicatorToContent: !widget.switchControl,
        child: widget.switchControl
            ? Switch(value: _value, onChanged: widget.enabled ? _change : null)
            : Checkbox(
                value: _value,
                onChanged: widget.enabled
                    ? (value) => _change(value ?? false)
                    : null,
              ),
      ),
      DFieldContent(
        children: [
          DFieldLabel(
            excludeSemantics: true,
            onPressed: () => _change(!_value),
            style: const TextStyle(fontWeight: FontWeight.w400),
            child: Text(widget.label),
          ),
          if (widget.description != null)
            DFieldDescription(child: Text(widget.description!)),
        ],
      ),
    ],
  );
}

class _Selection extends StatefulWidget {
  const _Selection(this.label, this.items, {this.description});
  final String label;
  final List<String> items;
  final String? description;
  @override
  State<_Selection> createState() => _SelectionState();
}

class _SelectionState extends State<_Selection> {
  final _focus = FocusNode();
  String? _value;
  @override
  void dispose() {
    _focus.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => DField(
    children: [
      DFieldLabel(
        focusNode: _focus,
        excludeSemantics: true,
        child: Text(widget.label),
      ),
      DFieldControl(
        label: widget.label,
        description: widget.description,
        child: DropdownButtonFormField<String>(
          focusNode: _focus,
          initialValue: _value,
          isExpanded: true,
          hint: const Text('Choose'),
          items: [
            for (final item in widget.items)
              DropdownMenuItem(value: item, child: Text(item)),
          ],
          onChanged: (value) => setState(() => _value = value),
        ),
      ),
      if (widget.description != null)
        DFieldDescription(child: Text(widget.description!)),
    ],
  );
}

class _Columns extends StatelessWidget {
  const _Columns({required this.children});
  final List<Widget> children;
  @override
  Widget build(BuildContext context) => LayoutBuilder(
    builder: (context, constraints) {
      final horizontal =
          constraints.maxWidth >= 360 &&
          MediaQuery.textScalerOf(context).scale(14) <= 21;
      return Flex(
        direction: horizontal ? Axis.horizontal : Axis.vertical,
        crossAxisAlignment: CrossAxisAlignment.start,
        mainAxisSize: MainAxisSize.min,
        children: [
          for (var i = 0; i < children.length; i++) ...[
            if (i > 0)
              SizedBox(width: horizontal ? 16 : 0, height: horizontal ? 0 : 16),
            Flexible(flex: horizontal ? 1 : 0, child: children[i]),
          ],
        ],
      );
    },
  );
}

class FieldNotificationsExample extends StatefulWidget {
  const FieldNotificationsExample({super.key});
  @override
  State<FieldNotificationsExample> createState() =>
      _FieldNotificationsExampleState();
}

class _FieldNotificationsExampleState extends State<FieldNotificationsExample> {
  bool _manage = false;
  @override
  Widget build(BuildContext context) => DFieldGroup(
    children: [
      const DFieldSet(
        children: [
          DFieldLegend(
            variant: DFieldLegendVariant.label,
            child: Text('Responses'),
          ),
          DFieldDescription(
            child: Text(
              'Get notified when ChatGPT responds to requests that take time, like research or image generation.',
            ),
          ),
          _Choice('Push notifications', initial: true, enabled: false),
        ],
      ),
      const DFieldSeparator(child: Text('Notification preferences')),
      DFieldSet(
        children: [
          const DFieldLegend(
            variant: DFieldLegendVariant.label,
            child: Text('Tasks'),
          ),
          const DFieldDescription(
            child: Text("Get notified when tasks you've created have updates."),
          ),
          DButton(
            label: Text(_manage ? 'Hide tasks' : 'Manage tasks'),
            onPressed: () => setState(() => _manage = !_manage),
          ),
          if (_manage) const Text('No local tasks.'),
          const DFieldGroup(
            variant: DFieldGroupVariant.choice,
            children: [
              _Choice('Push task notifications'),
              _Choice('Email notifications'),
            ],
          ),
        ],
      ),
      const _Choice('Multi-factor authentication', switchControl: true),
    ],
  );
}

''',
  'responsive': r'''import 'package:discourse_native/discourse_ui.dart';
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: Scaffold(body: SingleChildScrollView(padding: const EdgeInsets.all(24), child: FieldResponsiveExample()))));

class _Editor extends StatefulWidget {
  const _Editor(
    this.label, {
    this.description,
    this.placeholder,
    this.required = false,
    this.lines = 1,
    this.obscure = false,
    this.helpBefore = false,
  });
  final String label;
  final String? description;
  final String? placeholder;
  final bool required;
  final int lines;
  final bool obscure;
  final bool helpBefore;
  @override
  State<_Editor> createState() => _EditorState();
}

class _EditorState extends State<_Editor> {
  final _focus = FocusNode();
  @override
  void dispose() {
    _focus.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => DField(
    children: [
      DFieldLabel(
        focusNode: _focus,
        excludeSemantics: true,
        child: Text(widget.label),
      ),
      if (widget.helpBefore && widget.description != null)
        DFieldDescription(child: Text(widget.description!)),
      DFieldControl(
        label: widget.label,
        description: widget.description,
        required: widget.required,
        child: TextFormField(
          focusNode: _focus,
          maxLines: widget.lines,
          obscureText: widget.obscure,
          decoration: InputDecoration(
            hintText: widget.placeholder,
            errorMaxLines: 4,
            border: const OutlineInputBorder(),
          ),
          validator: widget.required
              ? (value) =>
                    value == null || value.trim().isEmpty ? 'Required' : null
              : null,
        ),
      ),
      if (!widget.helpBefore && widget.description != null)
        DFieldDescription(child: Text(widget.description!)),
    ],
  );
}

class _Choice extends StatefulWidget {
  const _Choice(
    this.label, {
    this.description,
    this.initial = false,
    this.enabled = true,
    this.switchControl = false,
  });
  final String label;
  final String? description;
  final bool initial;
  final bool enabled;
  final bool switchControl;
  @override
  State<_Choice> createState() => _ChoiceState();
}

class _ChoiceState extends State<_Choice> {
  late bool _value = widget.initial;
  void _change(bool value) => setState(() => _value = value);
  @override
  Widget build(BuildContext context) => DField(
    enabled: widget.enabled,
    orientation: DFieldOrientation.horizontal,
    children: [
      DFieldControl(
        label: widget.label,
        description: widget.description,
        expand: false,
        alignIndicatorToContent: !widget.switchControl,
        child: widget.switchControl
            ? Switch(value: _value, onChanged: widget.enabled ? _change : null)
            : Checkbox(
                value: _value,
                onChanged: widget.enabled
                    ? (value) => _change(value ?? false)
                    : null,
              ),
      ),
      DFieldContent(
        children: [
          DFieldLabel(
            excludeSemantics: true,
            onPressed: () => _change(!_value),
            style: const TextStyle(fontWeight: FontWeight.w400),
            child: Text(widget.label),
          ),
          if (widget.description != null)
            DFieldDescription(child: Text(widget.description!)),
        ],
      ),
    ],
  );
}

class _Selection extends StatefulWidget {
  const _Selection(this.label, this.items, {this.description});
  final String label;
  final List<String> items;
  final String? description;
  @override
  State<_Selection> createState() => _SelectionState();
}

class _SelectionState extends State<_Selection> {
  final _focus = FocusNode();
  String? _value;
  @override
  void dispose() {
    _focus.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => DField(
    children: [
      DFieldLabel(
        focusNode: _focus,
        excludeSemantics: true,
        child: Text(widget.label),
      ),
      DFieldControl(
        label: widget.label,
        description: widget.description,
        child: DropdownButtonFormField<String>(
          focusNode: _focus,
          initialValue: _value,
          isExpanded: true,
          hint: const Text('Choose'),
          items: [
            for (final item in widget.items)
              DropdownMenuItem(value: item, child: Text(item)),
          ],
          onChanged: (value) => setState(() => _value = value),
        ),
      ),
      if (widget.description != null)
        DFieldDescription(child: Text(widget.description!)),
    ],
  );
}

class _Columns extends StatelessWidget {
  const _Columns({required this.children});
  final List<Widget> children;
  @override
  Widget build(BuildContext context) => LayoutBuilder(
    builder: (context, constraints) {
      final horizontal =
          constraints.maxWidth >= 360 &&
          MediaQuery.textScalerOf(context).scale(14) <= 21;
      return Flex(
        direction: horizontal ? Axis.horizontal : Axis.vertical,
        crossAxisAlignment: CrossAxisAlignment.start,
        mainAxisSize: MainAxisSize.min,
        children: [
          for (var i = 0; i < children.length; i++) ...[
            if (i > 0)
              SizedBox(width: horizontal ? 16 : 0, height: horizontal ? 0 : 16),
            Flexible(flex: horizontal ? 1 : 0, child: children[i]),
          ],
        ],
      );
    },
  );
}

class FieldResponsiveExample extends StatefulWidget {
  const FieldResponsiveExample({super.key});
  @override
  State<FieldResponsiveExample> createState() => _FieldResponsiveExampleState();
}

class _FieldResponsiveExampleState extends State<FieldResponsiveExample> {
  final _form = GlobalKey<FormState>();
  final _focus = FocusNode();
  final _text = TextEditingController();
  String? _saved;
  @override
  void dispose() {
    _focus.dispose();
    _text.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => Form(
    key: _form,
    child: DFieldSet(
      children: [
        const DFieldLegend(child: Text('Profile')),
        const DFieldDescription(
          child: Text('Fill in your profile information.'),
        ),
        DFieldGroup(
          children: [
            FormField<String>(
              initialValue: '',
              onReset: _text.clear,
              onSaved: (value) => _saved = value,
              validator: (value) => (value ?? '').trim().isEmpty
                  ? 'Provide your full name.'
                  : null,
              builder: (state) {
                final errors = [state.errorText];
                return DField(
                  orientation: DFieldOrientation.responsive,
                  invalid: state.hasError,
                  children: [
                    DFieldContent(
                      children: [
                        DFieldLabel(
                          focusNode: _focus,
                          excludeSemantics: true,
                          child: const Text('Name'),
                        ),
                        const DFieldDescription(
                          child: Text(
                            'Provide your full name for identification',
                          ),
                        ),
                      ],
                    ),
                    DFieldContent(
                      children: [
                        DFieldControl(
                          label: 'Name',
                          required: true,
                          description:
                              'Provide your full name for identification',
                          errors: errors,
                          child: TextField(
                            focusNode: _focus,
                            controller: _text,
                            decoration: const InputDecoration(
                              hintText: 'Evil Rabbit',
                              border: OutlineInputBorder(),
                            ),
                            onChanged: state.didChange,
                          ),
                        ),
                        if (state.hasError) DFieldError(errors: errors),
                      ],
                    ),
                  ],
                );
              },
            ),
            Wrap(
              spacing: 8,
              runSpacing: 8,
              children: [
                DButton(
                  label: const Text('Submit profile'),
                  onPressed: () {
                    if (_form.currentState!.validate()) {
                      setState(() => _form.currentState!.save());
                    }
                  },
                ),
                DButton(
                  label: const Text('Reset profile'),
                  onPressed: () {
                    _form.currentState!.reset();
                    setState(() => _saved = null);
                  },
                ),
              ],
            ),
            if (_saved != null)
              Semantics(
                liveRegion: true,
                child: Text('Saved locally: $_saved'),
              ),
            const DFieldError(
              errors: [
                null,
                'Example of multiple errors.',
                'Example of multiple errors.',
                'Each unique message appears once.',
              ],
            ),
          ],
        ),
      ],
    ),
  );
}
''',
  'rtl': r'''import 'package:discourse_native/discourse_ui.dart';
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: Scaffold(body: SingleChildScrollView(padding: const EdgeInsets.all(24), child: Directionality(textDirection: TextDirection.rtl, child: FieldPaymentExample(arabic: true))))));

class _Editor extends StatefulWidget {
  const _Editor(
    this.label, {
    this.description,
    this.placeholder,
    this.required = false,
    this.lines = 1,
    this.obscure = false,
    this.helpBefore = false,
  });
  final String label;
  final String? description;
  final String? placeholder;
  final bool required;
  final int lines;
  final bool obscure;
  final bool helpBefore;
  @override
  State<_Editor> createState() => _EditorState();
}

class _EditorState extends State<_Editor> {
  final _focus = FocusNode();
  @override
  void dispose() {
    _focus.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => DField(
    children: [
      DFieldLabel(
        focusNode: _focus,
        excludeSemantics: true,
        child: Text(widget.label),
      ),
      if (widget.helpBefore && widget.description != null)
        DFieldDescription(child: Text(widget.description!)),
      DFieldControl(
        label: widget.label,
        description: widget.description,
        required: widget.required,
        child: TextFormField(
          focusNode: _focus,
          maxLines: widget.lines,
          obscureText: widget.obscure,
          decoration: InputDecoration(
            hintText: widget.placeholder,
            errorMaxLines: 4,
            border: const OutlineInputBorder(),
          ),
          validator: widget.required
              ? (value) =>
                    value == null || value.trim().isEmpty ? 'Required' : null
              : null,
        ),
      ),
      if (!widget.helpBefore && widget.description != null)
        DFieldDescription(child: Text(widget.description!)),
    ],
  );
}

class _Choice extends StatefulWidget {
  const _Choice(
    this.label, {
    this.description,
    this.initial = false,
    this.enabled = true,
    this.switchControl = false,
  });
  final String label;
  final String? description;
  final bool initial;
  final bool enabled;
  final bool switchControl;
  @override
  State<_Choice> createState() => _ChoiceState();
}

class _ChoiceState extends State<_Choice> {
  late bool _value = widget.initial;
  void _change(bool value) => setState(() => _value = value);
  @override
  Widget build(BuildContext context) => DField(
    enabled: widget.enabled,
    orientation: DFieldOrientation.horizontal,
    children: [
      DFieldControl(
        label: widget.label,
        description: widget.description,
        expand: false,
        alignIndicatorToContent: !widget.switchControl,
        child: widget.switchControl
            ? Switch(value: _value, onChanged: widget.enabled ? _change : null)
            : Checkbox(
                value: _value,
                onChanged: widget.enabled
                    ? (value) => _change(value ?? false)
                    : null,
              ),
      ),
      DFieldContent(
        children: [
          DFieldLabel(
            excludeSemantics: true,
            onPressed: () => _change(!_value),
            style: const TextStyle(fontWeight: FontWeight.w400),
            child: Text(widget.label),
          ),
          if (widget.description != null)
            DFieldDescription(child: Text(widget.description!)),
        ],
      ),
    ],
  );
}

class _Selection extends StatefulWidget {
  const _Selection(this.label, this.items, {this.description});
  final String label;
  final List<String> items;
  final String? description;
  @override
  State<_Selection> createState() => _SelectionState();
}

class _SelectionState extends State<_Selection> {
  final _focus = FocusNode();
  String? _value;
  @override
  void dispose() {
    _focus.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => DField(
    children: [
      DFieldLabel(
        focusNode: _focus,
        excludeSemantics: true,
        child: Text(widget.label),
      ),
      DFieldControl(
        label: widget.label,
        description: widget.description,
        child: DropdownButtonFormField<String>(
          focusNode: _focus,
          initialValue: _value,
          isExpanded: true,
          hint: const Text('Choose'),
          items: [
            for (final item in widget.items)
              DropdownMenuItem(value: item, child: Text(item)),
          ],
          onChanged: (value) => setState(() => _value = value),
        ),
      ),
      if (widget.description != null)
        DFieldDescription(child: Text(widget.description!)),
    ],
  );
}

class _Columns extends StatelessWidget {
  const _Columns({required this.children});
  final List<Widget> children;
  @override
  Widget build(BuildContext context) => LayoutBuilder(
    builder: (context, constraints) {
      final horizontal =
          constraints.maxWidth >= 360 &&
          MediaQuery.textScalerOf(context).scale(14) <= 21;
      return Flex(
        direction: horizontal ? Axis.horizontal : Axis.vertical,
        crossAxisAlignment: CrossAxisAlignment.start,
        mainAxisSize: MainAxisSize.min,
        children: [
          for (var i = 0; i < children.length; i++) ...[
            if (i > 0)
              SizedBox(width: horizontal ? 16 : 0, height: horizontal ? 0 : 16),
            Flexible(flex: horizontal ? 1 : 0, child: children[i]),
          ],
        ],
      );
    },
  );
}

class FieldPaymentExample extends StatefulWidget {
  const FieldPaymentExample({super.key, this.arabic = false});
  final bool arabic;
  @override
  State<FieldPaymentExample> createState() => _FieldPaymentExampleState();
}

class _FieldPaymentExampleState extends State<FieldPaymentExample> {
  final _form = GlobalKey<FormState>();
  int _reset = 0;
  String? _saved;
  @override
  Widget build(BuildContext context) {
    final ar = widget.arabic;
    return Form(
      key: _form,
      child: DFieldGroup(
        children: [
          DFieldSet(
            children: [
              DFieldLegend(child: Text(ar ? 'طريقة الدفع' : 'Payment Method')),
              DFieldDescription(
                child: Text(
                  ar
                      ? 'جميع المعاملات آمنة ومشفرة'
                      : 'All transactions are secure and encrypted',
                ),
              ),
              DFieldGroup(
                children: [
                  _Editor(
                    ar ? 'الاسم على البطاقة' : 'Name on Card',
                    placeholder: 'Evil Rabbit',
                    required: true,
                  ),
                  _Editor(
                    ar ? 'رقم البطاقة' : 'Card Number',
                    placeholder: '1234 5678 9012 3456',
                    required: true,
                    description: ar
                        ? 'أدخل رقم البطاقة المكون من 16 رقمًا'
                        : 'Enter your 16-digit card number',
                  ),
                  _Columns(
                    children: [
                      _Selection(ar ? 'الشهر' : 'Month', const [
                        '01',
                        '02',
                        '03',
                        '04',
                        '05',
                        '06',
                        '07',
                        '08',
                        '09',
                        '10',
                        '11',
                        '12',
                      ]),
                      _Selection(ar ? 'السنة' : 'Year', const [
                        '2024',
                        '2025',
                        '2026',
                        '2027',
                        '2028',
                        '2029',
                      ]),
                      const _Editor('CVV', placeholder: '123', required: true),
                    ],
                  ),
                ],
              ),
            ],
          ),
          const DFieldSeparator(),
          DFieldSet(
            children: [
              DFieldLegend(
                child: Text(ar ? 'عنوان الفوترة' : 'Billing Address'),
              ),
              DFieldDescription(
                child: Text(
                  ar
                      ? 'عنوان الفوترة المرتبط بطريقة الدفع الخاصة بك'
                      : 'The billing address associated with your payment method',
                ),
              ),
              KeyedSubtree(
                key: ValueKey(_reset),
                child: _Choice(
                  ar ? 'نفس عنوان الشحن' : 'Same as shipping address',
                  initial: true,
                ),
              ),
            ],
          ),
          _Editor(
            ar ? 'تعليقات' : 'Comments',
            lines: 3,
            placeholder: ar
                ? 'أضف أي تعليقات إضافية'
                : 'Add any additional comments',
          ),
          Wrap(
            spacing: 8,
            runSpacing: 8,
            children: [
              DButton(
                label: Text(ar ? 'إرسال' : 'Submit'),
                onPressed: () {
                  if (_form.currentState!.validate()) {
                    setState(
                      () => _saved = ar ? 'تم الحفظ محليًا' : 'Saved locally',
                    );
                  }
                },
              ),
              DButton(
                label: Text(ar ? 'إلغاء' : 'Cancel'),
                onPressed: () {
                  _form.currentState!.reset();
                  setState(() {
                    _reset++;
                    _saved = null;
                  });
                },
              ),
            ],
          ),
          if (_saved != null) Semantics(liveRegion: true, child: Text(_saved!)),
        ],
      ),
    );
  }
}

''',
};
