import 'examples/accordion_examples.dart';
import 'examples/alert_dialog_examples.dart';
import 'examples/alert_examples.dart';
import 'examples/aspect_ratio_examples.dart';
import 'examples/attachment_examples.dart';
import 'examples/avatar_examples.dart';
import 'examples/badge_examples.dart';
import 'examples/bubble_examples.dart';
import 'examples/button_examples.dart';
import 'examples/calendar_examples.dart';
import 'examples/card_examples.dart';
import 'examples/carousel_examples.dart';
import 'examples/chart_examples.dart';
import 'examples/checkbox_examples.dart';
import 'examples/collapsible_examples.dart';
import 'examples/combobox_examples.dart';
import 'examples/command_examples.dart';
import 'examples/date_picker_examples.dart';
import 'examples/dialog_examples.dart';
import 'examples/direction_examples.dart';
import 'examples/drawer_examples.dart';
import 'examples/dropdown_menu_examples.dart';
import 'examples/empty_examples.dart';
import 'examples/field_examples.dart';
import 'examples/foundation_examples.dart';
import 'examples/hover_card_examples.dart';
import 'examples/input_examples.dart';
import 'examples/input_group_examples.dart';
import 'examples/input_otp_examples.dart';
import 'examples/item_examples.dart';
import 'examples/kbd_examples.dart';
import 'examples/label_examples.dart';
import 'examples/marker_examples.dart';
import 'examples/message_examples.dart';
import 'examples/message_scroller_examples.dart';
import 'examples/native_select_examples.dart';
import 'examples/pagination_examples.dart';
import 'examples/popover_examples.dart';
import 'examples/progress_examples.dart';
import 'examples/questionnaire_examples.dart';
import 'examples/radio_group_examples.dart';
import 'examples/resizable_examples.dart';
import 'examples/scroll_area_examples.dart';
import 'examples/select_examples.dart';
import 'examples/separator_examples.dart';
import 'examples/sheet_examples.dart';
import 'examples/sidebar_examples.dart';
import 'examples/skeleton_examples.dart';
import 'examples/slider_examples.dart';
import 'examples/spinner_examples.dart';
import 'examples/switch_examples.dart';
import 'examples/table_examples.dart';
import 'examples/tabs_examples.dart';
import 'examples/textarea_examples.dart';
import 'examples/toast_examples.dart';
import 'examples/toggle_examples.dart';
import 'examples/toggle_group_examples.dart';
import 'examples/tooltip_examples.dart';
import 'examples/typography_examples.dart';
import 'styleguide_example.dart';

/// Each component task replaces its baseline or adds its own example file.
final componentExamples = <String, ComponentExamples>{
  'date-picker': datePickerExamples,
  'accordion': accordionExamples,
  'alert': alertExamples,
  'alert-dialog': alertDialogExamples,
  'table': tableExamples,
  'textarea': textareaExamples,
  'input-group': inputGroupExamples,
  'collapsible': collapsibleExamples,
  'combobox': comboboxExamples,
  'command': commandExamples,
  'input': inputExamples,
  'input-otp': inputOTPExamples,
  'radio-group': radioGroupExamples,
  'checkbox': checkboxExamples,
  'item': itemExamples,
  'empty': emptyExamples,
  'calendar': calendarExamples,
  'card': cardExamples,
  'carousel': carouselExamples,
  'chart': chartExamples,
  'resizable': resizableExamples,
  'foundations': foundationExamples,
  'hover-card': hoverCardExamples,
  'aspect-ratio': aspectRatioExamples,
  'attachment': attachmentExamples,
  'avatar': avatarExamples,
  'badge': badgeExamples,
  'bubble': bubbleExamples,
  'dialog': dialogExamples,
  'dropdown-menu': dropdownMenuExamples,
  'drawer': drawerExamples,
  'direction': directionExamples,
  'typography': typographyExamples,
  'scroll-area': scrollAreaExamples,
  'separator': separatorExamples,
  'sheet': sheetExamples,
  'kbd': kbdExamples,
  'label': labelExamples,
  'native-select': nativeSelectExamples,
  'pagination': paginationExamples,
  'field': fieldExamples,
  'progress': progressExamples,
  'questionnaire': questionnaireExamples,
  'marker': markerExamples,
  'message': messageExamples,
  'message-scroller': messageScrollerExamples,
  'popover': popoverExamples,
  'skeleton': skeletonExamples,
  'sidebar': sidebarExamples,
  'spinner': spinnerExamples,
  'slider': sliderExamples,
  'switch': switchExamples,
  'tabs': tabsExamples,
  'toggle': toggleExamples,
  'toast': toastExamples,
  'toggle-group': toggleGroupExamples,
  'button': buttonExamples,
  'tooltip': tooltipExamples,
  'select': selectExamples,
};
